#!/usr/bin/env python3
"""
Copy ONLY the 48 flags Probaball uses into public/flags/4x3/ and generate
src/flags-min.css that references them by URL. This replaces importing the full
flag-icons CSS (~260 flags inlined, ~89 KB gzipped). The CSS itself is tiny;
each flag SVG is a separate static file that the browser fetches lazily, only
when a flag is actually rendered (and then caches). Re-run after changing the
team list:  python3 build-flags-css.py
"""
import os
import shutil

# Must match TEAM_ISO values in src/flags.jsx.
CODES = [
    "mx", "za", "kr", "cz", "ca", "ch", "qa", "ba", "br", "ma", "gb-sct", "ht",
    "us", "py", "au", "tr", "de", "cw", "ci", "ec", "nl", "jp", "tn", "se",
    "be", "eg", "ir", "nz", "es", "cv", "sa", "uy", "fr", "sn", "no", "iq",
    "ar", "dz", "at", "jo", "pt", "co", "uz", "cd", "gb-eng", "hr", "gh", "pa",
]

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "node_modules", "flag-icons", "flags", "4x3")
DEST = os.path.join(HERE, "public", "flags", "4x3")
CSS = os.path.join(HERE, "src", "flags-min.css")

BASE = """/* AUTO-GENERATED by build-flags-css.py — only the 48 flags Probaball uses.
   SVGs live in public/flags/4x3/ and load lazily per rendered flag. */
.fi {
  background-size: contain;
  background-position: 50%;
  background-repeat: no-repeat;
  position: relative;
  display: inline-block;
  width: 1.33333333em;
  line-height: 1em;
}
.fi:before { content: "\\00a0"; }
"""


def main():
    os.makedirs(DEST, exist_ok=True)
    rules = [BASE]
    for code in CODES:
        src = os.path.join(SRC, f"{code}.svg")
        if not os.path.exists(src):
            raise SystemExit(f"missing flag svg: {src}")
        shutil.copyfile(src, os.path.join(DEST, f"{code}.svg"))
        rules.append(f'.fi-{code}{{background-image:url("/flags/4x3/{code}.svg")}}')
    with open(CSS, "w", encoding="utf-8") as f:
        f.write("\n".join(rules) + "\n")
    print(f"copied {len(CODES)} flags to {DEST}; wrote {CSS} "
          f"({os.path.getsize(CSS)} bytes)")


if __name__ == "__main__":
    main()
