import { createContext, useContext, useEffect, useState } from "react";

// Core 6 languages. Swedish is the source; English is the fallback/international
// default. Detection is browser-locale only (no external service).
export const LANGS = {
  sv: "Svenska", en: "English", es: "Español",
  fr: "Français", pt: "Português", de: "Deutsch",
};
const SUPPORTED = Object.keys(LANGS);

// Localized country (team) names, keyed by the engine's Swedish name. Swedish
// is the identity (the key itself).
export const TEAM_NAMES = {
  en: { Mexiko: "Mexico", Sydafrika: "South Africa", Sydkorea: "South Korea", Tjeckien: "Czechia", Kanada: "Canada", Schweiz: "Switzerland", Qatar: "Qatar", Bosnien: "Bosnia", Brasilien: "Brazil", Marocko: "Morocco", Skottland: "Scotland", Haiti: "Haiti", USA: "USA", Paraguay: "Paraguay", Australien: "Australia", Turkiet: "Turkey", Tyskland: "Germany", Curacao: "Curaçao", Elfenbenskusten: "Ivory Coast", Ecuador: "Ecuador", Nederländerna: "Netherlands", Japan: "Japan", Tunisien: "Tunisia", Sverige: "Sweden", Belgien: "Belgium", Egypten: "Egypt", Iran: "Iran", "Nya Zeeland": "New Zealand", Spanien: "Spain", "Kap Verde": "Cape Verde", Saudiarabien: "Saudi Arabia", Uruguay: "Uruguay", Frankrike: "France", Senegal: "Senegal", Norge: "Norway", Irak: "Iraq", Argentina: "Argentina", Algeriet: "Algeria", Österrike: "Austria", Jordanien: "Jordan", Portugal: "Portugal", Colombia: "Colombia", Uzbekistan: "Uzbekistan", "DR Kongo": "DR Congo", England: "England", Kroatien: "Croatia", Ghana: "Ghana", Panama: "Panama" },
  es: { Mexiko: "México", Sydafrika: "Sudáfrica", Sydkorea: "Corea del Sur", Tjeckien: "Chequia", Kanada: "Canadá", Schweiz: "Suiza", Qatar: "Catar", Bosnien: "Bosnia", Brasilien: "Brasil", Marocko: "Marruecos", Skottland: "Escocia", Haiti: "Haití", USA: "EE. UU.", Paraguay: "Paraguay", Australien: "Australia", Turkiet: "Turquía", Tyskland: "Alemania", Curacao: "Curazao", Elfenbenskusten: "Costa de Marfil", Ecuador: "Ecuador", Nederländerna: "Países Bajos", Japan: "Japón", Tunisien: "Túnez", Sverige: "Suecia", Belgien: "Bélgica", Egypten: "Egipto", Iran: "Irán", "Nya Zeeland": "Nueva Zelanda", Spanien: "España", "Kap Verde": "Cabo Verde", Saudiarabien: "Arabia Saudí", Uruguay: "Uruguay", Frankrike: "Francia", Senegal: "Senegal", Norge: "Noruega", Irak: "Irak", Argentina: "Argentina", Algeriet: "Argelia", Österrike: "Austria", Jordanien: "Jordania", Portugal: "Portugal", Colombia: "Colombia", Uzbekistan: "Uzbekistán", "DR Kongo": "RD Congo", England: "Inglaterra", Kroatien: "Croacia", Ghana: "Ghana", Panama: "Panamá" },
  fr: { Mexiko: "Mexique", Sydafrika: "Afrique du Sud", Sydkorea: "Corée du Sud", Tjeckien: "Tchéquie", Kanada: "Canada", Schweiz: "Suisse", Qatar: "Qatar", Bosnien: "Bosnie", Brasilien: "Brésil", Marocko: "Maroc", Skottland: "Écosse", Haiti: "Haïti", USA: "États-Unis", Paraguay: "Paraguay", Australien: "Australie", Turkiet: "Turquie", Tyskland: "Allemagne", Curacao: "Curaçao", Elfenbenskusten: "Côte d'Ivoire", Ecuador: "Équateur", Nederländerna: "Pays-Bas", Japan: "Japon", Tunisien: "Tunisie", Sverige: "Suède", Belgien: "Belgique", Egypten: "Égypte", Iran: "Iran", "Nya Zeeland": "Nouvelle-Zélande", Spanien: "Espagne", "Kap Verde": "Cap-Vert", Saudiarabien: "Arabie saoudite", Uruguay: "Uruguay", Frankrike: "France", Senegal: "Sénégal", Norge: "Norvège", Irak: "Irak", Argentina: "Argentine", Algeriet: "Algérie", Österrike: "Autriche", Jordanien: "Jordanie", Portugal: "Portugal", Colombia: "Colombie", Uzbekistan: "Ouzbékistan", "DR Kongo": "RD Congo", England: "Angleterre", Kroatien: "Croatie", Ghana: "Ghana", Panama: "Panama" },
  pt: { Mexiko: "México", Sydafrika: "África do Sul", Sydkorea: "Coreia do Sul", Tjeckien: "Chéquia", Kanada: "Canadá", Schweiz: "Suíça", Qatar: "Catar", Bosnien: "Bósnia", Brasilien: "Brasil", Marocko: "Marrocos", Skottland: "Escócia", Haiti: "Haiti", USA: "EUA", Paraguay: "Paraguai", Australien: "Austrália", Turkiet: "Turquia", Tyskland: "Alemanha", Curacao: "Curaçao", Elfenbenskusten: "Costa do Marfim", Ecuador: "Equador", Nederländerna: "Países Baixos", Japan: "Japão", Tunisien: "Tunísia", Sverige: "Suécia", Belgien: "Bélgica", Egypten: "Egito", Iran: "Irã", "Nya Zeeland": "Nova Zelândia", Spanien: "Espanha", "Kap Verde": "Cabo Verde", Saudiarabien: "Arábia Saudita", Uruguay: "Uruguai", Frankrike: "França", Senegal: "Senegal", Norge: "Noruega", Irak: "Iraque", Argentina: "Argentina", Algeriet: "Argélia", Österrike: "Áustria", Jordanien: "Jordânia", Portugal: "Portugal", Colombia: "Colômbia", Uzbekistan: "Uzbequistão", "DR Kongo": "RD Congo", England: "Inglaterra", Kroatien: "Croácia", Ghana: "Gana", Panama: "Panamá" },
  de: { Mexiko: "Mexiko", Sydafrika: "Südafrika", Sydkorea: "Südkorea", Tjeckien: "Tschechien", Kanada: "Kanada", Schweiz: "Schweiz", Qatar: "Katar", Bosnien: "Bosnien", Brasilien: "Brasilien", Marocko: "Marokko", Skottland: "Schottland", Haiti: "Haiti", USA: "USA", Paraguay: "Paraguay", Australien: "Australien", Turkiet: "Türkei", Tyskland: "Deutschland", Curacao: "Curaçao", Elfenbenskusten: "Elfenbeinküste", Ecuador: "Ecuador", Nederländerna: "Niederlande", Japan: "Japan", Tunisien: "Tunesien", Sverige: "Schweden", Belgien: "Belgien", Egypten: "Ägypten", Iran: "Iran", "Nya Zeeland": "Neuseeland", Spanien: "Spanien", "Kap Verde": "Kap Verde", Saudiarabien: "Saudi-Arabien", Uruguay: "Uruguay", Frankrike: "Frankreich", Senegal: "Senegal", Norge: "Norwegen", Irak: "Irak", Argentina: "Argentinien", Algeriet: "Algerien", Österrike: "Österreich", Jordanien: "Jordanien", Portugal: "Portugal", Colombia: "Kolumbien", Uzbekistan: "Usbekistan", "DR Kongo": "DR Kongo", England: "England", Kroatien: "Kroatien", Ghana: "Ghana", Panama: "Panama" },
};

const STRINGS = {
  sv: {
    lede_head: 'Så här kommer VM 2026 att gå.', lede_basis_pre: 'Baserat på ranking, ledande oddsmakare och experter har Krukis Data Science byggt en kombinerad simuleringsmodell och ', lede_count: 'spelar turneringen {n} gånger varje dag', lede_basis_post: '. Så här gick det.', lede_cta_pre: 'Har du en egen uppfattning om vissa matcher kan du ', lede_cta_link: 'göra en egen simulering', lede_cta_post: '.',
    lede_exp: "Din egen simulering. Vi körde turneringen {n} gånger med dina justeringar{forced}. Så här gick det.",
    lede_loading: 'Så här kommer VM 2026 att gå. Baserat på ranking, ledande oddsmakare och experter har Krukis Data Science byggt en kombinerad simuleringsmodell.',
    forced_suffix: " och {n} bestämda matcher",
    loading: "Laddar simulering…",
    see_sources: "Se källor", basis_date: "underlag {date}", error_load: "Kunde inte ladda data: {error}",
    sec_champion: "Världsmästare", sec_groups: "Gruppspel", sec_bracket: "Slutspelsträd", sec_experiment: "Din egen simulering", sec_faq: "Vanliga frågor",
    hint_team: "Klicka på ett lag för detaljer.", hint_group: "Klicka på en grupp för matchprognoser och grupptabell.",
    groups_legend: "Stapeln visar chansen att gå vidare: fylld del = topp 2 (direktkval), ljus del = 3:e plats (de 8 bästa treorna av 12 går också vidare).",
    bracket_help: "Den genomspelning som bäst speglar det förväntade utfallet: de mest sannolika lagen i varje slutspelsrunda. Klicka för ett nytt sådant utfall.",
    reroll: "↻ Nytt utfall", experiment_hint: "Ändra modellen och kör en egen simulering.",
    col_team: "Lag", col_champion: "Mästare", col_final: "Final", col_semi: "Semi", col_quarter: "Kvart", col_r16: "R16",
    show_all: "Visa alla {n} lag", show_top10: "Visa topp 10",
    group_label: "Grupp {g}", details: "detaljer →", g_first: "1:a", g_second: "2:a", g_third: "3:a", g_fourth: "4:a", g_top2: "Topp 2", g_avg: "Ø plac.",
    ctrl_params: "Modellparametrar", ctrl_goal_scale: "Favoritfördel", ctrl_goal_scale_hint: "Hur mycket styrkeskillnaden avgör. Högre → favoriter vinner oftare.", ctrl_base_goals: "Antal mål", ctrl_base_goals_hint: "Förväntat antal mål i en jämn match. Högre → fler mål och mer slump.", ctrl_home_adv: "Hemmafördel", ctrl_home_adv_hint: "Hur stor fördel värdnationerna (USA, Mexiko, Kanada) får i gruppspelet.", ctrl_rho: "Oavgjort-tendens", ctrl_rho_hint: "Högre → fler oavgjorda och lågmålade matcher.",
    ctrl_run: "Kör min simulering (1000)", ctrl_running: "Simulerar…", ctrl_reset: "Återställ reglage", ctrl_back: "← Till kanoniskt underlag", ctrl_conviction: "Bestäm matcher", ctrl_conviction_hint: " — välj ett lag som alltid slår ett annat",
    cv_winner_ph: "Lag som vinner…", cv_beats: "slår", cv_opponent_ph: "Motståndare…", cv_x_wins: "{team} vinner", cv_add: "+ Lägg till", cv_empty: "Inga matcher bestämda än. Välj ett lag som alltid slår ett annat – varje gång de möts i simuleringen vinner ditt lag.",
    close: "Stäng",
    tm_subtitle: "{group} · effektiv rating {r}", tm_matches: "Matcher", tm_chart_h: "Titeloddsens resa", tm_ko_note: "prognos · {pct} sannolikt", tm_ko_adv: "{pct} vidare", tm_ko_split: "{reg} på 90 · {et} förl./straffar", ko_reg_lbl: "i ordinarie", ko_et_lbl: "förl./straffar", tm_pred: "{pct} vinst", tm_placement: "Slutplacering", tm_placement_hint: "Andel av simuleringarna per slutplacering (1 = mästare … 33–48 = ut i gruppspelet).", tm_x_placement: "Placering (1–48)", tm_y_share: "Sannolikhet", col_change_7d: "Förändring", col_change_7d_hint: "Förändring i vinstchans sedan turneringen startade", eliminated_hint: "Utslaget — 0 % chans att gå vidare", trend_label: "Den här veckan", read_more: "Läs mer", read_less: "Visa mindre", trend_up: "{team} är veckans största klättrare, från {from}:a till {to}:a.", trend_up2: "{team} klättrade också, till {to}:a.", trend_down: "{team} tappade mest, från {from}:a till {to}:a.", tm_champ_up: "Mer sannolik mästare än vid turneringsstart, ändrat från {from} % till {to} %", tm_champ_down: "Mindre sannolik mästare än vid turneringsstart, ändrat från {from} % till {to} %", tm_vs_week: "{v} sedan turneringsstart", tm_progress: "Hur långt laget når", tm_x_round: "Slutspelsrunda", tm_group_place: "Gruppspelsplacering", tm_x_group: "Placering i gruppen", tm_rnd_final: "Final", tm_rnd_semi: "Semi", tm_rnd_quarter: "Kvart", tm_rnd_r16: "R16", tm_rnd_r32: "R32", tm_rnd_group: "Grupp", tm_no_group: "Ingen gruppdata.", tm_rnd_third: "Brons", tm_pens: "straffar", tm_basis: "Underlag (47.5 % · 47.5 % · 5 %)", tm_fifa: "FIFA-ranking", tm_fifa_rank: "#{r} av 48 i turneringen", tm_world_rank: " · världsrank #{r}", tm_books: "Bookmakers", tm_book_chance: "≈ {pct} titelchans", tm_experts: "Experter", tm_expert_weight: "vikt {pct}", tm_book_odds: "Bookmakerodds (vinna VM)", tm_expert_preds: "Expertprediktioner", tm_no_experts: "Ingen av de {n} experterna har tippat detta lag.",
    role_winner: "mästare", role_finalist: "finalist", role_semifinalist: "semifinal",
    gm_subtitle: "Simulerad slutplacering – sannolikhet för varje position", gm_note: "Mörkare zon = topp 2 (direktkval). Ljusare = 3:e plats: de åtta bästa treorna av tolv går också vidare till slutspelet.",
    eval_link: "Utvärdering", eval_title: "Hur bra är prognosen?", eval_subtitle: "Modellens prognoser före match, mätta mot resultaten",
    eval_empty: "Inga matcher är spelade ännu — kom tillbaka när turneringen har börjat.",
    eval_chart_h: "Så har titelracet förändrats", eval_chart_help: "Varje lags chans att vinna VM, dag för dag sedan 30 maj.", eval_rps: "Snitt-RPS", eval_lower_better: "lägre är bättre · 0 = perfekt", eval_games: "Bedömda matcher", eval_so_far: "gruppspel hittills",
    eval_called: "Rätt favorit", eval_called_exp: "väntat ~{exp}", eval_upsets: "Skrällar", eval_upsets_exp: "väntat ~{exp}",
    eval_rps_info: "Ranked Probability Score är det vedertagna vetenskapliga måttet för fotbollsprognoser: det belönar sannolikhet lagd nära det faktiska resultatet och respekterar ordningen hemma–oavgjort–borta, så en nära miss straffas mindre än en vild. Lägre är bättre; 0 är en perfekt prognos.",
    eval_bench: "Som referens: publicerade modeller ligger runt 0,19–0,22 RPS i ligafotboll och skarpa spelbolagsodds kring 0,20. Internationella turneringar beter sig annorlunda, så se detta som en grov måttstock, inte ett mål.",
    eval_cite: "Mått: Constantinou & Fenton (2012), Journal of Quantitative Analysis in Sports 8(1).",
    eval_upset_inline: "Hittills har {m} av {n} matcher blivit skrällar — ett utfall modellen gav under {p}. Den väntade sig ungefär {exp}, så resultaten ligger i linje med förväntan.",
    eval_upset_more: "Hittills har {m} av {n} matcher blivit skrällar — ett utfall modellen gav under {p}. Den väntade sig ungefär {exp}, så det har varit mer dramatik än väntat.",
    eval_upset_fewer: "Hittills har bara {m} av {n} matcher blivit skrällar — ett utfall modellen gav under {p}. Den väntade sig ungefär {exp}, så det har gått mer enligt formboken än väntat.",
    eval_calib_h: "Kalibrering", eval_calib_help: "När modellen säger att ett utfall är X% sannolikt, inträffar det X% av gångerna? Punkter på diagonalen är perfekt kalibrerade; ovanför linjen inträffade det oftare än väntat, nedanför mer sällan.",
    eval_calib_x: "Förutsagt %", eval_calib_y: "Observerat %", eval_calib_ideal: "Perfekt kalibrering", eval_calib_model: "Modellen hittills",
    eval_smallN: "Med bara en handfull matcher är punkterna skakiga — de stabiliseras när fler matcher spelats.",
    eval_games_h: "Match för match", eval_p_actual: "modellen gav {p}",
    sm_title: "Källor", sm_subtitle: "Sannolikheterna väger 47,5 % rankingar, 47,5 % bookmakers, 5 % experter", sm_rank_h: "Lagrankingar (Elo)", sm_fifa_desc: "Lagens styrka kommer från en Elo-rating beräknad från ~50 000 landskamper. (FIFA-rankingen testades men tillförde inget utöver Elo och används inte.)", sm_books: "Ledande oddsmakare", sm_books_desc: "Vinnarodds insamlade slutet av maj 2026.", sm_experts_n: "Experter ({n})", sm_tips: "Tippar som mästare", sm_goal_h: "Målmodell (oavgjort)", sm_host_h: "Hemmafördel (värdnationer)", ref_elo: "Rankingar använder World Football Elo-metoden (eloratings.net).", ref_books: "Marknadsodds hör till de mest träffsäkra utfallsprognoserna (Forrest, Goddard & Simmons, 2005).", ref_goal: "Resultaten dras med en Dixon–Coles-målmodell som korrigerar låg-mål- och oavgjort-bias (Dixon & Coles, 1997).", ref_host: "Värdnationer får en hemmafördel – baserad på forskning om hemmafördel (Pollard, 1986); storleken är kalibrerad på tidigare VM.", sm_footer: "Underlag uppdaterat {date}. Probaball är inte anslutet till eller godkänt av FIFA.",
    hm_title: "Hur räknar Probaball?", hm_subtitle: "Kort om modellen bakom siffrorna", hm_h_idea: "Idén", hm_idea: "Ingen vet hur VM slutar. Så i stället för att gissa en vinnare spelar Probaball upp hela turneringen om och om igen – tusentals gånger. Starkare lag vinner oftare, och hur ofta ett lag når en viss runda blir dess sannolikhet.", hm_h_strength: "Hur starkt är ett lag?", hm_strength: "Varje lags styrka är en viktad blandning (47,5 % rankingar, 47,5 % bookmakers, 5 % experter):", hm_li_fifa: "Rankingar – en Elo-rating från ~50 000 landskamper (FIFA-rankingen tillförde inget extra i testerna).", hm_li_books: "Oddsmakare – vinnarodds från {books}, omräknade till sannolikheter.", hm_li_experts: "Experter – {n} kända tippare och expertmodeller (t.ex. ESPN, Lineker, Opta).", hm_blend: "Vi väger ihop de tre till ett gemensamt styrketal.", hm_h_match: "Hur avgörs en match?", hm_match: "Antalet mål lottas slumpmässigt (en Poisson-modell), där det starkare laget väntas göra fler mål. Värdnationerna får hemmafördel i gruppspelet; oavgjort i slutspel avgörs på straffar.", hm_h_conviction: "Bestämda matcher", hm_conviction: "Tror du stenhårt på ett visst resultat? Lägg in en bestämd match – då vinner ditt lag varje gång lagen möts, och du ser hur oddsen ändras.", hm_h_note: "Bra att veta", hm_note: "Det här är en modell, inte en spådom. Probaball är inte anslutet till eller godkänt av FIFA.",
    cc_eyebrow: "Ditt lag", cc_stat: "{pct} att vinna VM", cc_change: "Det där är inte mitt lag – byt", set_myteam: "Markera som mitt lag", is_myteam: "✓ Ditt lag",
    how_link: "Hur räknar Probaball?", code_link: "Öppen källkod", code_title: "Öppen källkod", code_subtitle: "Hela modellen och den här sajten är öppna", code_lede: "En prognos är bara så trovärdig som den är genomskinlig. Därför är hela Probaball — datan, modellen, simuleringen och den här webappen — öppen källkod under MIT-licens. Granska den, ifrågasätt den, återanvänd den.", code_cta: "Se koden på GitHub →", code_what_h: "Vad finns i repot", code_what_data: "Datainsamling — Elo från ~50 000 landskamper, vinnarodds och experttips, sammanvägt till varje lags styrka.", code_what_model: "Modellen — en Monte Carlo-motor som spelar upp turneringen med 48 lag tiotusentals gånger.", code_what_backtest: "Backtest & kalibrering — out-of-sample-mått (RPS) som dömer varje modelländring.", code_what_web: "Webappen — den här sajten (React + Vite), på sex språk.", code_data_h: "Data & licens", code_data: "Bygger på öppna och offentliga källor. MIT-licens. En statistisk prognos, inte en spådom — och inte ansluten till eller godkänd av FIFA.", theme_day: "☀️ Dagläge", theme_night: "🌙 Nattläge", lang_label: "Språk",
    faq_q1: "Hur räknar Probaball ut vem som vinner fotbolls-VM 2026?", faq_a1: "Probaball är en data science-simulering (Monte Carlo) som spelar upp hela fotbolls-VM 2026 tiotusentals gånger. Varje lags styrka är en viktad blandning av tre oberoende källor – lagrankingar (Elo, beräknad från ~50 000 landskamper), bookmakeroddsen och {n} experters tips – och matcherna avgörs med en Dixon-Coles-målmodell i det officiella slutspelsträdet. Andelen simuleringar där ett lag vinner blir lagets sannolikhet.",
    faq_q2: "Vilka är favoriter till att vinna VM 2026?", faq_a2: "I Probaballs simulering är {fav} favorit med {favPct}, följt av {second} och {third}. Ordningen kombinerar ranking, odds och experttips.",
    faq_q3: "Vad baseras Probaballs odds på?", faq_a3: "Tre källor vägs samman (47,5 % rankingar, 47,5 % bookmakers, 5 % experter): lagrankingar med Elo i botten (FIFA-rankingen visade sig inte tillföra något extra i våra tester), avvigade vinnarodds från {books}, och prediktioner från {n} experter och statistiska modeller.",
    faq_q4: "Kan jag göra en egen simulering?", faq_a4: "Ja. Du kan justera parametrarna och tvinga utfallet i enskilda matcher och köra om data science-simuleringen för att se hur sannolikheterna ändras.",
    faq_q5: "Är Probaball anslutet till FIFA?", faq_a5: "Nej. Probaball är ett oberoende data science-projekt och är inte anslutet till eller godkänt av FIFA.",
    faq_q6: 'Hur avancerad är modellen – och hur träffsäker?', faq_a6: 'Probaball väger samman många oberoende signaler till en prognos – ungefär som när man slår ihop många opinionsmätningar till ett snitt (en “poll of polls”). Den bygger på en Elo-rating från ~50 000 landskamper, marknadens odds, expertmodeller, en Dixon-Coles-målmodell och det officiella slutspelsträdet. Viktigt: varje förbättring testas mot historiska resultat (out-of-sample, med Ranked Probability Score) och det som inte gör prognosen bättre slängs – t.ex. visade det sig att FIFA-rankingen och en attack/försvars-modell inte tillförde något. Men det är sannolikheter, inte facit: fotboll är slumpartat, och även en storfavorit hamnar oftast under 20 % chans att vinna hela turneringen.',
    tm_elo: 'Elo-rating', gm_results: 'Sannolika utfall', gm_matchday: 'Omgång {n}', gm_draw: 'Oavgjort', gm_wins: '{team} vinner', gm_as_pred: 'som väntat', gm_upset: 'skräll', gm_detail: 'detalj', mm_score: 'Sannolikaste resultat: {a}–{b}', mm_prematch: 'Modellens odds före match', gm_likely: 'sannol. {hg}–{ag}',
    back_home: "← Tillbaka", page_team_title: "{team} – chans att vinna VM 2026", page_group_title: "Grupp {g} – VM 2026",
  },
  en: {
    lede_head: "Here's how the 2026 World Cup will go.", lede_basis_pre: 'Based on rankings, leading bookmakers and experts, Krukis Data Science built a combined simulation model and ', lede_count: 'play the tournament {n} times every day', lede_basis_post: ". Here's how it turned out.", lede_cta_pre: 'Got your own read on certain matches? You can ', lede_cta_link: 'run your own simulation', lede_cta_post: '.',
    lede_exp: "Your own simulation. We ran the tournament {n} times with your tweaks{forced}. Here's how it turned out.",
    lede_loading: "Here's how the 2026 World Cup will go. Based on rankings, leading bookmakers and experts, Krukis Data Science built a combined simulation model.",
    forced_suffix: " and {n} decided matches",
    loading: "Loading simulation…",
    see_sources: "See sources", basis_date: "data {date}", error_load: "Couldn't load data: {error}",
    sec_champion: "World champion", sec_groups: "Group stage", sec_bracket: "Knockout bracket", sec_experiment: "Your own simulation", sec_faq: "FAQ",
    hint_team: "Click a team for details.", hint_group: "Click a group for match predictions and standings.",
    groups_legend: "The bar shows advancement chance: filled = top 2 (direct), faint = 3rd place (the 8 best third-placed teams of 12 also advance).",
    bracket_help: "The single run that best illustrates the expected outcome: the most likely teams in each knockout round. Click for another such run.",
    reroll: "↻ New outcome", experiment_hint: "Change the model and run your own simulation.",
    col_team: "Team", col_champion: "Champion", col_final: "Final", col_semi: "Semi", col_quarter: "QF", col_r16: "R16",
    show_all: "Show all {n} teams", show_top10: "Show top 10",
    group_label: "Group {g}", details: "details →", g_first: "1st", g_second: "2nd", g_third: "3rd", g_fourth: "4th", g_top2: "Top 2", g_avg: "Avg pos.",
    ctrl_params: "Model parameters", ctrl_goal_scale: "Favourite edge", ctrl_goal_scale_hint: "How much the strength gap decides. Higher → favourites win more often.", ctrl_base_goals: "Goals per match", ctrl_base_goals_hint: "Expected goals in an even match. Higher → more goals and more randomness.", ctrl_home_adv: "Home advantage", ctrl_home_adv_hint: "How big an edge the hosts (USA, Mexico, Canada) get in the group stage.", ctrl_rho: "Draw tendency", ctrl_rho_hint: "Higher → more draws and low-scoring games.",
    ctrl_run: "Run my simulation (1000)", ctrl_running: "Simulating…", ctrl_reset: "Reset sliders", ctrl_back: "← Back to canonical", ctrl_conviction: "Decide a match", ctrl_conviction_hint: " — pick a team that always beats another",
    cv_winner_ph: "Winning team…", cv_beats: "beats", cv_opponent_ph: "Opponent…", cv_x_wins: "{team} wins", cv_add: "+ Add", cv_empty: "No matches decided yet. Pick a team that always beats another – whenever they meet in the simulation, your team wins.",
    close: "Close",
    tm_subtitle: "{group} · effective rating {r}", tm_matches: "Matches", tm_chart_h: "Title-odds journey", tm_ko_note: "projected · {pct} likely", tm_ko_adv: "{pct} to advance", tm_ko_split: "{reg} in 90′ · {et} ET/pens", ko_reg_lbl: "in 90′", ko_et_lbl: "extra time / pens", tm_pred: "{pct} to win", tm_placement: "Final position", tm_placement_hint: "Share of simulations per final position (1 = champion … 33–48 = out in the group stage).", tm_x_placement: "Position (1–48)", tm_y_share: "Likelihood", col_change_7d: "Change", col_change_7d_hint: "Change in title chance since the tournament started", eliminated_hint: "Eliminated — 0% chance to advance", trend_label: "This week", read_more: "Read more", read_less: "Show less", trend_up: "{team} is the week's biggest climber, from {from} to {to}.", trend_up2: "{team} also rose, to {to}.", trend_down: "{team} slipped the most, from {from} to {to}.", tm_champ_up: "More likely to win than at kickoff, changed from {from}% to {to}%", tm_champ_down: "Less likely to win than at kickoff, changed from {from}% to {to}%", tm_vs_week: "{v} since kickoff", tm_progress: "How far the team gets", tm_x_round: "Knockout round", tm_group_place: "Group-stage finish", tm_x_group: "Position in the group", tm_rnd_final: "Final", tm_rnd_semi: "Semi", tm_rnd_quarter: "Quarter", tm_rnd_r16: "R16", tm_rnd_r32: "R32", tm_rnd_group: "Group", tm_no_group: "No group data.", tm_rnd_third: "3rd", tm_pens: "pens", tm_basis: "Inputs (47.5 % · 47.5 % · 5 %)", tm_fifa: "FIFA ranking", tm_fifa_rank: "#{r} of 48 in the tournament", tm_world_rank: " · world rank #{r}", tm_books: "Bookmakers", tm_book_chance: "≈ {pct} title chance", tm_experts: "Experts", tm_expert_weight: "weight {pct}", tm_book_odds: "Bookmaker odds (to win)", tm_expert_preds: "Expert predictions", tm_no_experts: "None of the {n} experts picked this team.",
    role_winner: "champion", role_finalist: "finalist", role_semifinalist: "semifinal",
    gm_subtitle: "Simulated final standings – probability for each position", gm_note: "Darker zone = top 2 (direct qualification); lighter = 3rd place. The eight best third-placed teams of twelve also advance to the Round of 32.",
    eval_link: "Evaluation", eval_title: "How good is the forecast?", eval_subtitle: "The model's pre-match predictions, scored against the results",
    eval_empty: "No games have been played yet — check back once the tournament is under way.",
    eval_chart_h: "How the title race has shifted", eval_chart_help: "Each team's chance to win the World Cup, day by day since 30 May.", eval_rps: "Average RPS", eval_lower_better: "lower is better · 0 = perfect", eval_games: "Games scored", eval_so_far: "group stage so far",
    eval_called: "Top pick right", eval_called_exp: "expected ~{exp}", eval_upsets: "Upsets", eval_upsets_exp: "expected ~{exp}",
    eval_rps_info: "The Ranked Probability Score is the standard scientific metric for football forecasts: it rewards probability placed close to the actual result and respects the home–draw–away ordering, so a near miss is punished less than a wild one. Lower is better; 0 is a perfect call.",
    eval_bench: "For reference, published models score roughly 0.19–0.22 RPS on league football and sharp bookmaker odds sit near 0.20. International tournaments behave differently, so treat these as a rough yardstick, not a target.",
    eval_cite: "Metric: Constantinou & Fenton (2012), Journal of Quantitative Analysis in Sports 8(1).",
    eval_upset_inline: "So far {m} of {n} games have been upsets — an outcome the model rated under {p}. It expected about {exp}, so results are in line with expectations.",
    eval_upset_more: "So far {m} of {n} games have been upsets — an outcome the model rated under {p}. It expected about {exp}, so it's been more eventful than expected.",
    eval_upset_fewer: "So far only {m} of {n} games have been upsets — an outcome the model rated under {p}. It expected about {exp}, so results have gone more to form than expected.",
    eval_calib_h: "Calibration", eval_calib_help: "When the model calls an outcome X% likely, does it happen X% of the time? Points on the diagonal are perfectly calibrated; above the line it happened more often than predicted, below it less.",
    eval_calib_x: "Predicted %", eval_calib_y: "Observed %", eval_calib_ideal: "Perfect calibration", eval_calib_model: "Model so far",
    eval_smallN: "With only a handful of games the dots are noisy — they'll settle as more matches are played.",
    eval_games_h: "Game by game", eval_p_actual: "model gave {p}",
    sm_title: "Sources", sm_subtitle: "The probabilities weight 47.5% rankings, 47.5% bookmakers, 5% experts", sm_rank_h: "Team rankings (Elo)", sm_fifa_desc: "Team strength comes from an Elo rating computed over ~50,000 internationals. (The FIFA ranking was tested but added nothing beyond Elo, so it isn't used.)", sm_books: "Leading bookmakers", sm_books_desc: "Title odds collected late May 2026.", sm_experts_n: "Experts ({n})", sm_tips: "Picks as champion", sm_goal_h: "Goal model (draws)", sm_host_h: "Host advantage", ref_elo: "Rankings use the World Football Elo method (eloratings.net).", ref_books: "Market odds are among the most accurate outcome forecasts (Forrest, Goddard & Simmons, 2005).", ref_goal: "Scorelines use a Dixon–Coles goal model that corrects the low-score and draw bias (Dixon & Coles, 1997).", ref_host: "Host nations get a home edge — grounded in home-advantage research (Pollard, 1986); the size is calibrated on past World Cups.", sm_footer: "Data updated {date}. Probaball is not affiliated with or endorsed by FIFA.",
    hm_title: "How does Probaball work?", hm_subtitle: "The model behind the numbers, in brief", hm_h_idea: "The idea", hm_idea: "Nobody knows how the World Cup ends. So instead of guessing one winner, Probaball plays the whole tournament out over and over – thousands of times. Stronger teams win more often, and how often a team reaches a given round becomes its probability.", hm_h_strength: "How strong is a team?", hm_strength: "Each team's strength is a weighted blend (47.5% rankings, 47.5% bookmakers, 5% experts):", hm_li_fifa: "Rankings – an Elo rating from ~50,000 internationals (the FIFA ranking added nothing extra in tests).", hm_li_books: "Bookmakers – title odds from {books}, converted to probabilities.", hm_li_experts: "Experts – {n} well-known pundits and models (e.g. ESPN, Lineker, Opta).", hm_blend: "We combine the three into a single strength rating.", hm_h_match: "How is a match decided?", hm_match: "Goals are drawn at random (a Poisson model) where the stronger team is expected to score more. Host nations get a home edge in the group stage; knockout ties are settled on penalties.", hm_h_conviction: "Fixed matches", hm_conviction: "Convinced about a result? Add a fixed match – your team then wins every time those teams meet, and you see how the odds shift.", hm_h_note: "Good to know", hm_note: "This is a model, not a prophecy. Probaball is not affiliated with or endorsed by FIFA.",
    cc_eyebrow: "Your team", cc_stat: "{pct} to win the World Cup", cc_change: "Not my team — change", set_myteam: "Set as my team", is_myteam: "✓ Your team",
    how_link: "How does Probaball work?", code_link: "Open source", code_title: "Open source", code_subtitle: "The whole model and this site are open", code_lede: "A forecast is only as trustworthy as it is transparent. So the whole of Probaball — the data, the model, the simulation and this web app — is open source under the MIT license. Inspect it, question it, reuse it.", code_cta: "View the code on GitHub →", code_what_h: "What's in the repo", code_what_data: "Data ingestion — Elo from ~50,000 internationals, bookmaker title odds and expert picks, blended into each team's strength.", code_what_model: "The model — a Monte Carlo engine that plays the 48-team tournament out tens of thousands of times.", code_what_backtest: "Backtest & calibration — out-of-sample scoring (RPS) that referees every model change.", code_what_web: "The web app — this site (React + Vite), in six languages.", code_data_h: "Data & license", code_data: "Built on open and public sources. MIT-licensed. A statistical forecast, not a prediction — and not affiliated with or endorsed by FIFA.", theme_day: "☀️ Day", theme_night: "🌙 Night", lang_label: "Language",
    faq_q1: "How does Probaball work out who wins the 2026 World Cup?", faq_a1: "Probaball is a data-science simulation (Monte Carlo) that plays the entire 2026 World Cup out tens of thousands of times. Each team's strength is a weighted blend of three independent sources — team ratings (Elo, computed from ~50,000 internationals), bookmaker odds, and {n} experts' tips — and matches are decided by a Dixon-Coles goal model in the official knockout bracket. The share of simulations a team wins is its probability.",
    faq_q2: "Who are the favorites to win the 2026 World Cup?", faq_a2: "In Probaball's simulation {fav} is the favorite with {favPct}, followed by {second} and {third}. The order combines ranking, odds and expert tips.",
    faq_q3: "What are Probaball's odds based on?", faq_a3: "Three sources are weighted together (47.5% rankings, 47.5% bookmakers, 5% experts): team ratings led by Elo (the FIFA ranking turned out to add nothing extra in our tests), de-vigged title odds from {books}, and predictions from {n} experts and statistical models.",
    faq_q4: "Can I run my own simulation?", faq_a4: "Yes. You can adjust the parameters and force the outcome of individual matches, then re-run the data-science simulation to see how the probabilities change.",
    faq_q5: "Is Probaball affiliated with FIFA?", faq_a5: "No. Probaball is an independent data-science project and is not affiliated with or endorsed by FIFA.",
    faq_q6: 'How sophisticated is the model — and how accurate?', faq_a6: "Probaball blends many independent signals into one forecast — much like averaging many polls into a single estimate (a “poll of polls”). It draws on an Elo rating from ~50,000 internationals, market odds, expert models, a Dixon-Coles goal model and the official knockout bracket. Crucially, every improvement is tested against historical results (out-of-sample, via the Ranked Probability Score) and anything that doesn't actually predict better is dropped — the FIFA ranking and an attack/defence model both turned out to add nothing. But these are probabilities, not certainties: football is high-variance, and even a strong favorite usually sits below a 20% chance to win the whole thing.",
    tm_elo: 'Elo rating', gm_results: 'Likely outcomes', gm_matchday: 'Matchday {n}', gm_draw: 'Draw', gm_wins: '{team} win', gm_as_pred: 'as predicted', gm_upset: 'upset', gm_detail: 'detail', mm_score: 'Most likely score: {a}–{b}', mm_prematch: "Model's pre-match odds", gm_likely: 'likely {hg}–{ag}',
    back_home: "← Back", page_team_title: "{team} – chance to win the 2026 World Cup", page_group_title: "Group {g} – 2026 World Cup",
  },
  es: {
    lede_head: 'Así será el Mundial 2026.', lede_basis_pre: 'A partir de rankings, las principales casas de apuestas y expertos, Krukis Data Science construyó un modelo de simulación combinado y ', lede_count: 'juega el torneo {n} veces cada día', lede_basis_post: '. Así quedó.', lede_cta_pre: '¿Tienes tu propia opinión sobre algunos partidos? Puedes ', lede_cta_link: 'hacer tu propia simulación', lede_cta_post: '.',
    lede_exp: "Tu propia simulación. Jugamos el torneo {n} veces con tus ajustes{forced}. Así quedó.",
    lede_loading: 'Así será el Mundial 2026. A partir de rankings, casas de apuestas y expertos, Krukis Data Science construyó un modelo de simulación combinado.',
    forced_suffix: " y {n} partidos decididos",
    loading: "Cargando simulación…",
    see_sources: "Ver fuentes", basis_date: "datos {date}", error_load: "No se pudieron cargar los datos: {error}",
    sec_champion: "Campeón del mundo", sec_groups: "Fase de grupos", sec_bracket: "Cuadro final", sec_experiment: "Tu propia simulación", sec_faq: "Preguntas frecuentes",
    hint_team: "Haz clic en un equipo para ver detalles.", hint_group: "Haz clic en un grupo para ver pronósticos y clasificación.",
    groups_legend: "La barra muestra la opción de avanzar: parte sólida = top 2 (directo), parte tenue = 3.er puesto (los 8 mejores terceros de 12 también avanzan).",
    bracket_help: "La simulación que mejor refleja el resultado esperado: los equipos más probables en cada ronda. Haz clic para otra.",
    reroll: "↻ Nuevo resultado", experiment_hint: "Cambia el modelo y haz tu propia simulación.",
    col_team: "Equipo", col_champion: "Campeón", col_final: "Final", col_semi: "Semi", col_quarter: "Cuartos", col_r16: "Octavos",
    show_all: "Ver los {n} equipos", show_top10: "Ver top 10",
    group_label: "Grupo {g}", details: "detalles →", g_first: "1.º", g_second: "2.º", g_third: "3.º", g_fourth: "4.º", g_top2: "Top 2", g_avg: "Pos. media",
    ctrl_params: "Parámetros del modelo", ctrl_goal_scale: "Ventaja del favorito", ctrl_goal_scale_hint: "Cuánto decide la diferencia de nivel. Mayor → los favoritos ganan más.", ctrl_base_goals: "Goles por partido", ctrl_base_goals_hint: "Goles esperados en un partido parejo. Mayor → más goles y más azar.", ctrl_home_adv: "Ventaja local", ctrl_home_adv_hint: "La ventaja de los anfitriones (EE. UU., México, Canadá) en la fase de grupos.", ctrl_rho: "Tendencia al empate", ctrl_rho_hint: "Mayor → más empates y partidos de pocos goles.",
    ctrl_run: "Ejecutar mi simulación (1000)", ctrl_running: "Simulando…", ctrl_reset: "Restablecer", ctrl_back: "← Volver al resultado base", ctrl_conviction: "Decide un partido", ctrl_conviction_hint: " — elige un equipo que siempre gane a otro",
    cv_winner_ph: "Equipo ganador…", cv_beats: "gana a", cv_opponent_ph: "Rival…", cv_x_wins: "Gana {team}", cv_add: "+ Añadir", cv_empty: "Aún no has decidido ningún partido. Elige un equipo que siempre gane a otro: cada vez que se crucen en la simulación, gana tu equipo.",
    close: "Cerrar",
    tm_subtitle: "{group} · rating efectivo {r}", tm_matches: "Partidos", tm_chart_h: "Evolución de su probabilidad de título", tm_ko_note: "proyectado · {pct} probable", tm_ko_adv: "{pct} de avanzar", tm_ko_split: "{reg} en 90′ · {et} pr./penales", ko_reg_lbl: "en 90′", ko_et_lbl: "pród./penales", tm_pred: "{pct} de victoria", tm_placement: "Posición final", tm_placement_hint: "Proporción de simulaciones por posición final (1 = campeón … 33–48 = eliminado en grupos).", tm_x_placement: "Posición (1–48)", tm_y_share: "Probabilidad", col_change_7d: "Cambio", col_change_7d_hint: "Cambio en la probabilidad de título desde el inicio del torneo", eliminated_hint: "Eliminado — 0 % de avanzar", trend_label: "Esta semana", read_more: "Leer más", read_less: "Mostrar menos", tm_champ_up: "Más probable campeón que al inicio del torneo, cambió del {from}% al {to}%", tm_champ_down: "Menos probable campeón que al inicio del torneo, cambió del {from}% al {to}%", tm_vs_week: "{v} desde el inicio", tm_progress: "Hasta dónde llega", tm_x_round: "Ronda eliminatoria", tm_group_place: "Posición en el grupo", tm_x_group: "Posición en el grupo", tm_rnd_final: "Final", tm_rnd_semi: "Semi", tm_rnd_quarter: "Cuartos", tm_rnd_r16: "R16", tm_rnd_r32: "R32", tm_rnd_group: "Grupos", tm_no_group: "Sin datos de grupo.", tm_rnd_third: "3.º", tm_pens: "penales", tm_basis: "Fuentes (47.5 % · 47.5 % · 5 %)", tm_fifa: "Ranking FIFA", tm_fifa_rank: "#{r} de 48 en el torneo", tm_world_rank: " · ranking mundial #{r}", tm_books: "Casas de apuestas", tm_book_chance: "≈ {pct} de ganar", tm_experts: "Expertos", tm_expert_weight: "peso {pct}", tm_book_odds: "Cuotas (para ganar)", tm_expert_preds: "Predicciones de expertos", tm_no_experts: "Ninguno de los {n} expertos eligió a este equipo.",
    role_winner: "campeón", role_finalist: "finalista", role_semifinalist: "semifinal",
    gm_subtitle: "Clasificación final simulada – probabilidad de cada posición", gm_note: "Zona más oscura = top 2 (clasificación directa); más clara = 3.er puesto. Los ocho mejores terceros de doce también avanzan a la Ronda de 32.",
    eval_link: "Evaluación", eval_title: "¿Qué tan buena es la predicción?", eval_subtitle: "Las predicciones del modelo antes del partido, medidas frente a los resultados",
    eval_empty: "Aún no se ha jugado ningún partido — vuelve cuando arranque el torneo.",
    eval_chart_h: "Cómo ha cambiado la lucha por el título", eval_chart_help: "La probabilidad de cada equipo de ganar el Mundial, día a día desde el 30 de mayo.", eval_rps: "RPS medio", eval_lower_better: "menos es mejor · 0 = perfecto", eval_games: "Partidos evaluados", eval_so_far: "fase de grupos hasta ahora",
    eval_called: "Favorito acertado", eval_called_exp: "esperado ~{exp}", eval_upsets: "Sorpresas", eval_upsets_exp: "esperado ~{exp}",
    eval_rps_info: "El Ranked Probability Score es la métrica científica estándar para pronósticos de fútbol: premia la probabilidad situada cerca del resultado real y respeta el orden local–empate–visitante, así que un fallo ajustado se castiga menos que uno disparatado. Menos es mejor; 0 es un pronóstico perfecto.",
    eval_bench: "Como referencia, los modelos publicados rondan 0,19–0,22 de RPS en fútbol de liga y las cuotas ajustadas de las casas se sitúan cerca de 0,20. Los torneos internacionales se comportan distinto, así que tómalo como una guía aproximada, no como un objetivo.",
    eval_cite: "Métrica: Constantinou & Fenton (2012), Journal of Quantitative Analysis in Sports 8(1).",
    eval_upset_inline: "Hasta ahora {m} de {n} partidos han sido sorpresas — un resultado que el modelo daba por debajo de {p}. Esperaba unas {exp}, así que los resultados van en línea con lo previsto.",
    eval_upset_more: "Hasta ahora {m} de {n} partidos han sido sorpresas — un resultado que el modelo daba por debajo de {p}. Esperaba unas {exp}, así que ha habido más emoción de la prevista.",
    eval_upset_fewer: "Hasta ahora solo {m} de {n} partidos han sido sorpresas — un resultado que el modelo daba por debajo de {p}. Esperaba unas {exp}, así que ha ido más conforme a la lógica de lo previsto.",
    eval_calib_h: "Calibración", eval_calib_help: "Cuando el modelo da a un resultado un X% de probabilidad, ¿ocurre el X% de las veces? Los puntos sobre la diagonal están perfectamente calibrados; por encima ocurrió más a menudo de lo previsto, por debajo menos.",
    eval_calib_x: "Previsto %", eval_calib_y: "Observado %", eval_calib_ideal: "Calibración perfecta", eval_calib_model: "Modelo hasta ahora",
    eval_smallN: "Con apenas un puñado de partidos los puntos son ruidosos — se estabilizarán a medida que se jueguen más.",
    eval_games_h: "Partido a partido", eval_p_actual: "el modelo daba {p}",
    sm_title: "Fuentes", sm_subtitle: "Las probabilidades pesan 47,5 % rankings, 47,5 % casas de apuestas, 5 % expertos", sm_rank_h: "Rankings de equipos (Elo)", sm_fifa_desc: "La fuerza surge de un rating Elo calculado sobre ~50 000 partidos internacionales. (El ranking FIFA se probó pero no aportó nada más allá del Elo, así que no se usa.)", sm_books: "Principales casas de apuestas", sm_books_desc: "Cuotas recogidas a finales de mayo de 2026.", sm_experts_n: "Expertos ({n})", sm_tips: "Lo elige campeón", sm_goal_h: "Modelo de goles (empates)", sm_host_h: "Ventaja de local", ref_elo: "Los rankings usan el método World Football Elo (eloratings.net).", ref_books: "Las cuotas del mercado están entre las predicciones de resultados más precisas (Forrest, Goddard & Simmons, 2005).", ref_goal: "Los marcadores usan un modelo de goles Dixon–Coles que corrige el sesgo de pocos goles y empates (Dixon & Coles, 1997).", ref_host: "Las anfitrionas tienen ventaja de local — basada en la investigación sobre ventaja de local (Pollard, 1986); su tamaño se calibra con Mundiales anteriores.", sm_footer: "Datos actualizados {date}. Probaball no está afiliado ni avalado por la FIFA.",
    hm_title: "¿Cómo calcula Probaball?", hm_subtitle: "El modelo detrás de las cifras, en breve", hm_h_idea: "La idea", hm_idea: "Nadie sabe cómo acaba el Mundial. Así que en vez de adivinar un ganador, Probaball juega el torneo entero una y otra vez, miles de veces. Los equipos más fuertes ganan más a menudo, y la frecuencia con que un equipo llega a una ronda se convierte en su probabilidad.", hm_h_strength: "¿Cómo de fuerte es un equipo?", hm_strength: "La fuerza de cada equipo es una mezcla ponderada (47,5 % rankings, 47,5 % casas de apuestas, 5 % expertos):", hm_li_fifa: "Rankings – un rating Elo de ~50 000 internacionales (el ranking FIFA no aportó nada extra en las pruebas).", hm_li_books: "Casas de apuestas – cuotas de {books}, convertidas en probabilidades.", hm_li_experts: "Expertos – {n} analistas y modelos conocidos (p. ej. ESPN, Lineker, Opta).", hm_blend: "Combinamos los tres en un único valor de fuerza.", hm_h_match: "¿Cómo se decide un partido?", hm_match: "Los goles se sortean al azar (un modelo de Poisson) donde el equipo más fuerte marca más. Los anfitriones tienen ventaja en la fase de grupos; los empates en eliminatorias se deciden por penaltis.", hm_h_conviction: "Partidos fijados", hm_conviction: "¿Convencido de un resultado? Añade un partido fijado: tu equipo ganará siempre que se crucen, y verás cómo cambian las probabilidades.", hm_h_note: "Bueno saber", hm_note: "Esto es un modelo, no una profecía. Probaball no está afiliado ni avalado por la FIFA.",
    cc_eyebrow: "Tu equipo", cc_stat: "{pct} de ganar el Mundial", cc_change: "Ese no es mi equipo — cambiar", set_myteam: "Marcar como mi equipo", is_myteam: "✓ Tu equipo",
    how_link: "¿Cómo calcula Probaball?", code_link: "Código abierto", code_title: "Código abierto", code_subtitle: "Todo el modelo y este sitio son abiertos", code_lede: "Una predicción solo es tan fiable como transparente. Por eso todo Probaball — los datos, el modelo, la simulación y esta web — es de código abierto con licencia MIT. Examínalo, cuestiónalo, reutilízalo.", code_cta: "Ver el código en GitHub →", code_what_h: "Qué hay en el repositorio", code_what_data: "Ingesta de datos — Elo de ~50 000 internacionales, cuotas de casas de apuestas y pronósticos de expertos, combinados en la fuerza de cada equipo.", code_what_model: "El modelo — un motor Monte Carlo que juega el torneo de 48 equipos decenas de miles de veces.", code_what_backtest: "Backtest y calibración — puntuación fuera de muestra (RPS) que arbitra cada cambio del modelo.", code_what_web: "La web — este sitio (React + Vite), en seis idiomas.", code_data_h: "Datos y licencia", code_data: "Construido sobre fuentes abiertas y públicas. Licencia MIT. Una predicción estadística, no un pronóstico seguro, y no afiliada ni avalada por la FIFA.", theme_day: "☀️ Día", theme_night: "🌙 Noche", lang_label: "Idioma",
    faq_q1: "¿Cómo calcula Probaball quién gana el Mundial 2026?", faq_a1: "Probaball es una simulación de data science (Monte Carlo) que juega el Mundial 2026 entero decenas de miles de veces. La fuerza de cada equipo es una mezcla ponderada de tres fuentes independientes —rankings de equipos (Elo, calculado a partir de ~50 000 partidos), las cuotas de las casas de apuestas y los pronósticos de {n} expertos— y los partidos se deciden con un modelo de goles Dixon-Coles en el cuadro oficial. La proporción de simulaciones que gana un equipo es su probabilidad.",
    faq_q2: "¿Quiénes son favoritos para ganar el Mundial 2026?", faq_a2: "En la simulación de Probaball {fav} es favorito con {favPct}, seguido de {second} y {third}. El orden combina ranking, cuotas y pronósticos de expertos.",
    faq_q3: "¿En qué se basan las cuotas de Probaball?", faq_a3: "Se combinan tres fuentes (47,5 % rankings, 47,5 % casas de apuestas, 5 % expertos): rankings liderados por Elo (el ranking FIFA no aportó nada extra en nuestras pruebas), cuotas sin margen de {books}, y predicciones de {n} expertos y modelos estadísticos.",
    faq_q4: "¿Puedo hacer mi propia simulación?", faq_a4: "Sí. Puedes ajustar los parámetros y forzar el resultado de partidos concretos, y volver a ejecutar la simulación para ver cómo cambian las probabilidades.",
    faq_q5: "¿Está Probaball afiliado a la FIFA?", faq_a5: "No. Probaball es un proyecto independiente de data science y no está afiliado ni avalado por la FIFA.",
    faq_q6: '¿Qué tan avanzado es el modelo y qué tan acertado?', faq_a6: 'Probaball combina muchas señales independientes en un solo pronóstico, parecido a promediar muchas encuestas en una sola (un “poll of polls”). Usa un Elo de ~50 000 partidos, las cuotas del mercado, modelos de expertos, un modelo de goles Dixon-Coles y el cuadro oficial. Importante: cada mejora se prueba contra resultados históricos (out-of-sample, con el Ranked Probability Score) y lo que no predice mejor se descarta — el ranking FIFA y un modelo de ataque/defensa no aportaron nada. Pero son probabilidades, no certezas: el fútbol es muy aleatorio, e incluso un gran favorito suele tener menos del 20 % de ganar el torneo.',
    tm_elo: 'Rating Elo', gm_results: 'Resultados probables', gm_matchday: 'Jornada {n}', gm_draw: 'Empate', gm_wins: 'Gana {team}', gm_as_pred: 'como previsto', gm_upset: 'sorpresa', gm_detail: 'detalle', mm_score: 'Resultado más probable: {a}–{b}', mm_prematch: 'Cuotas del modelo antes del partido', gm_likely: 'prob. {hg}–{ag}',
    back_home: "← Volver", page_team_title: "{team} – probabilidad de ganar el Mundial 2026", page_group_title: "Grupo {g} – Mundial 2026",
  },
  fr: {
    lede_head: 'Voici comment se déroulera la Coupe du monde 2026.', lede_basis_pre: 'À partir des classements, des principaux bookmakers et des experts, Krukis Data Science a construit un modèle de simulation combiné et ', lede_count: 'joue le tournoi {n} fois chaque jour', lede_basis_post: '. Voici le résultat.', lede_cta_pre: 'Vous avez votre propre avis sur certains matchs ? Vous pouvez ', lede_cta_link: 'lancer votre propre simulation', lede_cta_post: '.',
    lede_exp: "Votre propre simulation. Nous avons joué le tournoi {n} fois avec vos réglages{forced}. Voici le résultat.",
    lede_loading: 'Voici comment se déroulera la Coupe du monde 2026. À partir des classements, des bookmakers et des experts, Krukis Data Science a construit un modèle de simulation combiné.',
    forced_suffix: " et {n} matchs décidés",
    loading: "Chargement de la simulation…",
    see_sources: "Voir les sources", basis_date: "données {date}", error_load: "Impossible de charger les données : {error}",
    sec_champion: "Champion du monde", sec_groups: "Phase de groupes", sec_bracket: "Tableau final", sec_experiment: "Votre propre simulation", sec_faq: "FAQ",
    hint_team: "Cliquez sur une équipe pour les détails.", hint_group: "Cliquez sur un groupe pour les pronostics et le classement.",
    groups_legend: "La barre indique la chance de se qualifier : partie pleine = top 2 (direct), partie pâle = 3e place (les 8 meilleurs troisièmes sur 12 passent aussi).",
    bracket_help: "La simulation qui illustre le mieux le résultat attendu : les équipes les plus probables à chaque tour. Cliquez pour une autre.",
    reroll: "↻ Nouveau résultat", experiment_hint: "Modifiez le modèle et lancez votre propre simulation.",
    col_team: "Équipe", col_champion: "Champion", col_final: "Finale", col_semi: "Demi", col_quarter: "Quarts", col_r16: "8es",
    show_all: "Voir les {n} équipes", show_top10: "Voir le top 10",
    group_label: "Groupe {g}", details: "détails →", g_first: "1er", g_second: "2e", g_third: "3e", g_fourth: "4e", g_top2: "Top 2", g_avg: "Pos. moy.",
    ctrl_params: "Paramètres du modèle", ctrl_goal_scale: "Avantage du favori", ctrl_goal_scale_hint: "À quel point l'écart de niveau décide. Plus haut → les favoris gagnent plus souvent.", ctrl_base_goals: "Buts par match", ctrl_base_goals_hint: "Buts attendus dans un match équilibré. Plus haut → plus de buts et plus de hasard.", ctrl_home_adv: "Avantage du terrain", ctrl_home_adv_hint: "L'avantage des hôtes (États-Unis, Mexique, Canada) en phase de groupes.", ctrl_rho: "Tendance au nul", ctrl_rho_hint: "Plus haut → plus de nuls et de matchs à peu de buts.",
    ctrl_run: "Lancer ma simulation (1000)", ctrl_running: "Simulation…", ctrl_reset: "Réinitialiser", ctrl_back: "← Retour au résultat de base", ctrl_conviction: "Décidez un match", ctrl_conviction_hint: " — choisissez une équipe qui bat toujours une autre",
    cv_winner_ph: "Équipe gagnante…", cv_beats: "bat", cv_opponent_ph: "Adversaire…", cv_x_wins: "{team} gagne", cv_add: "+ Ajouter", cv_empty: "Aucun match décidé pour l'instant. Choisissez une équipe qui bat toujours une autre : à chaque rencontre dans la simulation, votre équipe gagne.",
    close: "Fermer",
    tm_subtitle: "{group} · note effective {r}", tm_matches: "Matchs", tm_chart_h: "Évolution de ses chances de titre", tm_ko_note: "projeté · {pct} probable", tm_ko_adv: "{pct} de passer", tm_ko_split: "{reg} en 90′ · {et} prol./tab", ko_reg_lbl: "en 90′", ko_et_lbl: "prol./tab", tm_pred: "{pct} de victoire", tm_placement: "Classement final", tm_placement_hint: "Part des simulations par classement final (1 = champion … 33–48 = éliminé en poules).", tm_x_placement: "Classement (1–48)", tm_y_share: "Probabilité", col_change_7d: "Évolution", col_change_7d_hint: "Évolution de la chance de titre depuis le début du tournoi", eliminated_hint: "Éliminé — 0 % de chances de passer", trend_label: "Cette semaine", read_more: "Lire la suite", read_less: "Réduire", tm_champ_up: "Plus de chances de titre qu'au coup d'envoi, de {from}% à {to}%", tm_champ_down: "Moins de chances de titre qu'au coup d'envoi, de {from}% à {to}%", tm_vs_week: "{v} depuis le début", tm_progress: "Jusqu'où va l'équipe", tm_x_round: "Tour à élimination", tm_group_place: "Classement en poule", tm_x_group: "Position dans le groupe", tm_rnd_final: "Finale", tm_rnd_semi: "Demi", tm_rnd_quarter: "Quart", tm_rnd_r16: "R16", tm_rnd_r32: "R32", tm_rnd_group: "Poules", tm_no_group: "Pas de données de groupe.", tm_rnd_third: "3e", tm_pens: "t.a.b.", tm_basis: "Sources (47.5 % · 47.5 % · 5 %)", tm_fifa: "Classement FIFA", tm_fifa_rank: "#{r} sur 48 dans le tournoi", tm_world_rank: " · rang mondial #{r}", tm_books: "Bookmakers", tm_book_chance: "≈ {pct} de titre", tm_experts: "Experts", tm_expert_weight: "poids {pct}", tm_book_odds: "Cotes (pour gagner)", tm_expert_preds: "Pronostics d'experts", tm_no_experts: "Aucun des {n} experts n'a choisi cette équipe.",
    role_winner: "champion", role_finalist: "finaliste", role_semifinalist: "demi-finale",
    gm_subtitle: "Classement final simulé – probabilité de chaque position", gm_note: "Zone plus foncée = top 2 (qualification directe) ; plus claire = 3e place. Les huit meilleurs troisièmes sur douze passent aussi au tour des 32.",
    eval_link: "Évaluation", eval_title: "Quelle est la qualité du pronostic ?", eval_subtitle: "Les pronostics du modèle avant match, confrontés aux résultats",
    eval_empty: "Aucun match n'a encore été joué — revenez une fois le tournoi lancé.",
    eval_chart_h: "Comment la course au titre a évolué", eval_chart_help: "La probabilité de chaque équipe de gagner la Coupe du monde, jour après jour depuis le 30 mai.", eval_rps: "RPS moyen", eval_lower_better: "plus bas est meilleur · 0 = parfait", eval_games: "Matchs évalués", eval_so_far: "phase de groupes jusqu'ici",
    eval_called: "Favori juste", eval_called_exp: "attendu ~{exp}", eval_upsets: "Surprises", eval_upsets_exp: "attendu ~{exp}",
    eval_rps_info: "Le Ranked Probability Score est la métrique scientifique de référence pour les pronostics de football : il récompense la probabilité placée près du résultat réel et respecte l'ordre victoire–nul–défaite, si bien qu'une erreur de peu est moins punie qu'une erreur grossière. Plus bas est meilleur ; 0 est un pronostic parfait.",
    eval_bench: "À titre de repère, les modèles publiés tournent autour de 0,19–0,22 de RPS en football de club et les cotes affûtées des bookmakers avoisinent 0,20. Les tournois internationaux se comportent différemment : à prendre comme repère approximatif, pas comme objectif.",
    eval_cite: "Métrique : Constantinou & Fenton (2012), Journal of Quantitative Analysis in Sports 8(1).",
    eval_upset_inline: "Jusqu'ici, {m} matchs sur {n} ont été des surprises — un résultat que le modèle jugeait sous {p}. Il en attendait environ {exp}, donc les résultats sont conformes aux attentes.",
    eval_upset_more: "Jusqu'ici, {m} matchs sur {n} ont été des surprises — un résultat que le modèle jugeait sous {p}. Il en attendait environ {exp}, donc cela a été plus mouvementé que prévu.",
    eval_upset_fewer: "Jusqu'ici, seulement {m} matchs sur {n} ont été des surprises — un résultat que le modèle jugeait sous {p}. Il en attendait environ {exp}, donc cela a davantage suivi la logique que prévu.",
    eval_calib_h: "Calibrage", eval_calib_help: "Quand le modèle annonce un résultat à X%, se produit-il X% du temps ? Les points sur la diagonale sont parfaitement calibrés ; au-dessus, c'est arrivé plus souvent que prévu, en dessous moins.",
    eval_calib_x: "Prédit %", eval_calib_y: "Observé %", eval_calib_ideal: "Calibrage parfait", eval_calib_model: "Modèle jusqu'ici",
    eval_smallN: "Avec une poignée de matchs seulement, les points sont bruités — ils se stabiliseront au fil des rencontres.",
    eval_games_h: "Match par match", eval_p_actual: "le modèle donnait {p}",
    sm_title: "Sources", sm_subtitle: "Les probabilités pondèrent 47,5 % classements, 47,5 % bookmakers, 5 % experts", sm_rank_h: "Classements (Elo)", sm_fifa_desc: "La force vient d'un classement Elo calculé sur ~50 000 matchs internationaux. (Le classement FIFA a été testé mais n'apportait rien de plus que l'Elo, il n'est donc pas utilisé.)", sm_books: "Principaux bookmakers", sm_books_desc: "Cotes relevées fin mai 2026.", sm_experts_n: "Experts ({n})", sm_tips: "Le voit champion", sm_goal_h: "Modèle de buts (nuls)", sm_host_h: "Avantage du pays hôte", ref_elo: "Les classements utilisent la méthode World Football Elo (eloratings.net).", ref_books: "Les cotes du marché comptent parmi les prévisions de résultats les plus précises (Forrest, Goddard & Simmons, 2005).", ref_goal: "Les scores suivent un modèle de buts Dixon–Coles qui corrige le biais des faibles scores et des nuls (Dixon & Coles, 1997).", ref_host: "Les pays hôtes ont un avantage à domicile — fondé sur la recherche sur l'avantage du terrain (Pollard, 1986) ; son ampleur est calibrée sur les Coupes du monde passées.", sm_footer: "Données mises à jour le {date}. Probaball n'est ni affilié ni approuvé par la FIFA.",
    hm_title: "Comment Probaball calcule-t-il ?", hm_subtitle: "Le modèle derrière les chiffres, en bref", hm_h_idea: "L'idée", hm_idea: "Personne ne sait comment finit la Coupe du monde. Alors au lieu de deviner un vainqueur, Probaball rejoue tout le tournoi encore et encore – des milliers de fois. Les équipes plus fortes gagnent plus souvent, et la fréquence à laquelle une équipe atteint un tour devient sa probabilité.", hm_h_strength: "Quelle est la force d'une équipe ?", hm_strength: "La force de chaque équipe est un mélange pondéré (47,5 % classements, 47,5 % bookmakers, 5 % experts) :", hm_li_fifa: "Classements – un classement Elo sur ~50 000 matchs internationaux (le classement FIFA n'apportait rien de plus dans les tests).", hm_li_books: "Bookmakers – cotes de {books}, converties en probabilités.", hm_li_experts: "Experts – {n} pronostiqueurs et modèles connus (p. ex. ESPN, Lineker, Opta).", hm_blend: "Nous combinons les trois en une seule note de force.", hm_h_match: "Comment un match est-il décidé ?", hm_match: "Les buts sont tirés au hasard (un modèle de Poisson) où l'équipe la plus forte marque davantage. Les hôtes ont l'avantage en phase de groupes ; les matchs nuls à élimination se règlent aux tirs au but.", hm_h_conviction: "Matchs imposés", hm_conviction: "Convaincu d'un résultat ? Ajoutez un match imposé : votre équipe gagne à chaque rencontre, et vous voyez l'impact sur les cotes.", hm_h_note: "Bon à savoir", hm_note: "C'est un modèle, pas une prophétie. Probaball n'est ni affilié ni approuvé par la FIFA.",
    cc_eyebrow: "Votre équipe", cc_stat: "{pct} de gagner la Coupe du monde", cc_change: "Ce n'est pas mon équipe — changer", set_myteam: "Définir comme mon équipe", is_myteam: "✓ Votre équipe",
    how_link: "Comment Probaball calcule-t-il ?", code_link: "Code ouvert", code_title: "Code ouvert", code_subtitle: "Tout le modèle et ce site sont ouverts", code_lede: "Un pronostic ne vaut que par sa transparence. C'est pourquoi tout Probaball — les données, le modèle, la simulation et cette application web — est en open source sous licence MIT. Examinez-le, questionnez-le, réutilisez-le.", code_cta: "Voir le code sur GitHub →", code_what_h: "Ce que contient le dépôt", code_what_data: "Ingestion des données — Elo sur ~50 000 matchs internationaux, cotes des bookmakers et pronostics d'experts, combinés en une force par équipe.", code_what_model: "Le modèle — un moteur Monte Carlo qui rejoue le tournoi à 48 équipes des dizaines de milliers de fois.", code_what_backtest: "Backtest et calibration — un score hors échantillon (RPS) qui arbitre chaque changement du modèle.", code_what_web: "L'application web — ce site (React + Vite), en six langues.", code_data_h: "Données et licence", code_data: "Construit sur des sources ouvertes et publiques. Sous licence MIT. Un pronostic statistique, pas une prédiction — et ni affilié ni approuvé par la FIFA.", theme_day: "☀️ Jour", theme_night: "🌙 Nuit", lang_label: "Langue",
    faq_q1: "Comment Probaball détermine-t-il qui gagne la Coupe du monde 2026 ?", faq_a1: "Probaball est une simulation de data science (Monte Carlo) qui rejoue toute la Coupe du monde 2026 des dizaines de milliers de fois. La force de chaque équipe est un mélange pondéré de trois sources indépendantes — classements d'équipes (Elo, calculé sur ~50 000 matchs), cotes des bookmakers et pronostics de {n} experts — et les matchs sont décidés par un modèle de buts Dixon-Coles dans le tableau officiel. La part des simulations gagnées est la probabilité.",
    faq_q2: "Qui sont les favoris pour gagner la Coupe du monde 2026 ?", faq_a2: "Dans la simulation de Probaball, {fav} est favori avec {favPct}, suivi de {second} et {third}. L'ordre combine classement, cotes et pronostics d'experts.",
    faq_q3: "Sur quoi reposent les cotes de Probaball ?", faq_a3: "Trois sources sont pondérées (47,5 % classements, 47,5 % bookmakers, 5 % experts) : classements menés par l'Elo (le classement FIFA n'apportait rien de plus dans nos tests), cotes sans marge de {books}, et pronostics de {n} experts et modèles statistiques.",
    faq_q4: "Puis-je lancer ma propre simulation ?", faq_a4: "Oui. Vous pouvez ajuster les paramètres et forcer l'issue de matchs précis, puis relancer la simulation pour voir comment les probabilités changent.",
    faq_q5: "Probaball est-il affilié à la FIFA ?", faq_a5: "Non. Probaball est un projet indépendant de data science et n'est ni affilié ni approuvé par la FIFA.",
    faq_q6: 'Le modèle est-il avancé — et fiable ?', faq_a6: "Probaball combine de nombreux signaux indépendants en une seule prévision, un peu comme la moyenne de plusieurs sondages (un “poll of polls”). Il s'appuie sur un Elo calculé sur ~50 000 matchs, les cotes du marché, des modèles d'experts, un modèle de buts Dixon-Coles et le tableau officiel. Important : chaque amélioration est testée sur des résultats historiques (hors échantillon, via le Ranked Probability Score) et ce qui n'améliore pas la prévision est écarté — le classement FIFA et un modèle attaque/défense n'apportaient rien. Mais ce sont des probabilités, pas des certitudes : le football est très aléatoire, et même un grand favori est généralement sous les 20 % de remporter le tournoi.",
    tm_elo: 'Classement Elo', gm_results: 'Issues probables', gm_matchday: 'Journée {n}', gm_draw: 'Nul', gm_wins: '{team} gagne', gm_as_pred: 'comme prévu', gm_upset: 'surprise', gm_detail: 'détail', mm_score: 'Score le plus probable : {a}–{b}', mm_prematch: 'Cotes du modèle avant le match', gm_likely: 'prob. {hg}–{ag}',
    back_home: "← Retour", page_team_title: "{team} – chances de gagner la Coupe du monde 2026", page_group_title: "Groupe {g} – Coupe du monde 2026",
  },
  pt: {
    lede_head: 'Veja como será a Copa do Mundo 2026.', lede_basis_pre: 'Com base em rankings, nas principais casas de apostas e em especialistas, a Krukis Data Science construiu um modelo de simulação combinado e ', lede_count: 'joga o torneio {n} vezes todos os dias', lede_basis_post: '. Foi assim que ficou.', lede_cta_pre: 'Tem a sua própria opinião sobre alguns jogos? Você pode ', lede_cta_link: 'fazer a sua própria simulação', lede_cta_post: '.',
    lede_exp: "Sua própria simulação. Rodamos o torneio {n} vezes com os seus ajustes{forced}. Foi assim que ficou.",
    lede_loading: 'Veja como será a Copa do Mundo 2026. Com base em rankings, casas de apostas e especialistas, a Krukis Data Science construiu um modelo de simulação combinado.',
    forced_suffix: " e {n} jogos decididos",
    loading: "Carregando simulação…",
    see_sources: "Ver fontes", basis_date: "dados {date}", error_load: "Não foi possível carregar os dados: {error}",
    sec_champion: "Campeão mundial", sec_groups: "Fase de grupos", sec_bracket: "Chave do mata-mata", sec_experiment: "Sua própria simulação", sec_faq: "Perguntas frequentes",
    hint_team: "Clique em uma seleção para ver detalhes.", hint_group: "Clique em um grupo para ver prognósticos e classificação.",
    groups_legend: "A barra mostra a chance de avançar: parte cheia = top 2 (direto), parte clara = 3.º lugar (os 8 melhores terceiros de 12 também avançam).",
    bracket_help: "A simulação que melhor ilustra o resultado esperado: as seleções mais prováveis em cada fase. Clique para outra.",
    reroll: "↻ Novo resultado", experiment_hint: "Mude o modelo e rode a sua própria simulação.",
    col_team: "Seleção", col_champion: "Campeão", col_final: "Final", col_semi: "Semi", col_quarter: "Quartas", col_r16: "Oitavas",
    show_all: "Ver todas as {n}", show_top10: "Ver top 10",
    group_label: "Grupo {g}", details: "detalhes →", g_first: "1º", g_second: "2º", g_third: "3º", g_fourth: "4º", g_top2: "Top 2", g_avg: "Pos. média",
    ctrl_params: "Parâmetros do modelo", ctrl_goal_scale: "Vantagem do favorito", ctrl_goal_scale_hint: "O quanto a diferença de nível decide. Maior → favoritos vencem mais.", ctrl_base_goals: "Gols por jogo", ctrl_base_goals_hint: "Gols esperados num jogo equilibrado. Maior → mais gols e mais acaso.", ctrl_home_adv: "Vantagem de casa", ctrl_home_adv_hint: "A vantagem dos anfitriões (EUA, México, Canadá) na fase de grupos.", ctrl_rho: "Tendência a empates", ctrl_rho_hint: "Maior → mais empates e jogos de poucos gols.",
    ctrl_run: "Rodar minha simulação (1000)", ctrl_running: "Simulando…", ctrl_reset: "Redefinir", ctrl_back: "← Voltar ao resultado base", ctrl_conviction: "Decida um jogo", ctrl_conviction_hint: " — escolha uma seleção que sempre vence outra",
    cv_winner_ph: "Seleção vencedora…", cv_beats: "vence", cv_opponent_ph: "Adversário…", cv_x_wins: "{team} vence", cv_add: "+ Adicionar", cv_empty: "Nenhum jogo decidido ainda. Escolha uma seleção que sempre vence outra: sempre que se enfrentarem na simulação, a sua seleção vence.",
    close: "Fechar",
    tm_subtitle: "{group} · rating efetivo {r}", tm_matches: "Jogos", tm_chart_h: "Evolução da chance de título", tm_ko_note: "projetado · {pct} provável", tm_ko_adv: "{pct} de avançar", tm_ko_split: "{reg} em 90′ · {et} pr./pênaltis", ko_reg_lbl: "em 90′", ko_et_lbl: "pror./pênaltis", tm_pred: "{pct} de vitória", tm_placement: "Classificação final", tm_placement_hint: "Proporção de simulações por classificação final (1 = campeão … 33–48 = eliminado na fase de grupos).", tm_x_placement: "Classificação (1–48)", tm_y_share: "Probabilidade", col_change_7d: "Variação", col_change_7d_hint: "Variação na chance de título desde o início do torneio", eliminated_hint: "Eliminado — 0 % de avançar", trend_label: "Esta semana", read_more: "Ler mais", read_less: "Mostrar menos", tm_champ_up: "Mais provável campeã que no início do torneio, mudou de {from}% para {to}%", tm_champ_down: "Menos provável campeã que no início do torneio, mudou de {from}% para {to}%", tm_vs_week: "{v} desde o início", tm_progress: "Até onde a seleção chega", tm_x_round: "Fase do mata-mata", tm_group_place: "Posição no grupo", tm_x_group: "Posição no grupo", tm_rnd_final: "Final", tm_rnd_semi: "Semi", tm_rnd_quarter: "Quartas", tm_rnd_r16: "R16", tm_rnd_r32: "R32", tm_rnd_group: "Grupos", tm_no_group: "Sem dados do grupo.", tm_rnd_third: "3.º", tm_pens: "pênaltis", tm_basis: "Fontes (47.5 % · 47.5 % · 5 %)", tm_fifa: "Ranking FIFA", tm_fifa_rank: "#{r} de 48 no torneio", tm_world_rank: " · ranking mundial #{r}", tm_books: "Casas de apostas", tm_book_chance: "≈ {pct} de título", tm_experts: "Especialistas", tm_expert_weight: "peso {pct}", tm_book_odds: "Odds (para vencer)", tm_expert_preds: "Previsões de especialistas", tm_no_experts: "Nenhum dos {n} especialistas escolheu esta seleção.",
    role_winner: "campeão", role_finalist: "finalista", role_semifinalist: "semifinal",
    gm_subtitle: "Classificação final simulada – probabilidade de cada posição", gm_note: "Zona mais escura = top 2 (classificação direta); mais clara = 3.º lugar. As oito melhores terceiras de doze também avançam para a Ronda de 32.",
    eval_link: "Avaliação", eval_title: "Quão boa é a previsão?", eval_subtitle: "As previsões do modelo antes do jogo, medidas face aos resultados",
    eval_empty: "Ainda não foi disputado nenhum jogo — volta quando o torneio começar.",
    eval_chart_h: "Como a disputa pelo título mudou", eval_chart_help: "A chance de cada seleção de ganhar a Copa, dia a dia desde 30 de maio.", eval_rps: "RPS médio", eval_lower_better: "menor é melhor · 0 = perfeito", eval_games: "Jogos avaliados", eval_so_far: "fase de grupos até agora",
    eval_called: "Favorito certo", eval_called_exp: "esperado ~{exp}", eval_upsets: "Surpresas", eval_upsets_exp: "esperado ~{exp}",
    eval_rps_info: "O Ranked Probability Score é a métrica científica padrão para previsões de futebol: premeia a probabilidade colocada perto do resultado real e respeita a ordem casa–empate–fora, pelo que um erro por pouco é menos penalizado do que um disparatado. Menor é melhor; 0 é uma previsão perfeita.",
    eval_bench: "Como referência, os modelos publicados rondam 0,19–0,22 de RPS no futebol de liga e as odds afinadas das casas situam-se perto de 0,20. Os torneios internacionais comportam-se de forma diferente, por isso encara isto como uma bitola aproximada, não um objetivo.",
    eval_cite: "Métrica: Constantinou & Fenton (2012), Journal of Quantitative Analysis in Sports 8(1).",
    eval_upset_inline: "Até agora {m} de {n} jogos foram surpresas — um resultado que o modelo dava abaixo de {p}. Esperava cerca de {exp}, por isso os resultados estão em linha com o previsto.",
    eval_upset_more: "Até agora {m} de {n} jogos foram surpresas — um resultado que o modelo dava abaixo de {p}. Esperava cerca de {exp}, por isso tem sido mais agitado do que o previsto.",
    eval_upset_fewer: "Até agora apenas {m} de {n} jogos foram surpresas — um resultado que o modelo dava abaixo de {p}. Esperava cerca de {exp}, por isso correu mais conforme a lógica do que o previsto.",
    eval_calib_h: "Calibração", eval_calib_help: "Quando o modelo dá a um resultado X% de probabilidade, ele acontece X% das vezes? Os pontos sobre a diagonal estão perfeitamente calibrados; acima da linha aconteceu mais vezes do que o previsto, abaixo menos.",
    eval_calib_x: "Previsto %", eval_calib_y: "Observado %", eval_calib_ideal: "Calibração perfeita", eval_calib_model: "Modelo até agora",
    eval_smallN: "Com apenas um punhado de jogos os pontos são ruidosos — estabilizam à medida que mais jogos forem disputados.",
    eval_games_h: "Jogo a jogo", eval_p_actual: "o modelo dava {p}",
    sm_title: "Fontes", sm_subtitle: "As probabilidades ponderam 47,5 % rankings, 47,5 % casas de apostas, 5 % especialistas", sm_rank_h: "Rankings das seleções (Elo)", sm_fifa_desc: "A força vem de um rating Elo calculado sobre ~50 000 jogos internacionais. (O ranking FIFA foi testado mas não acrescentou nada além do Elo, por isso não é usado.)", sm_books: "Principais casas de apostas", sm_books_desc: "Odds coletadas no fim de maio de 2026.", sm_experts_n: "Especialistas ({n})", sm_tips: "Aposta como campeão", sm_goal_h: "Modelo de gols (empates)", sm_host_h: "Vantagem de anfitrião", ref_elo: "Os rankings usam o método World Football Elo (eloratings.net).", ref_books: "As odds de mercado estão entre as previsões de resultados mais precisas (Forrest, Goddard & Simmons, 2005).", ref_goal: "Os placares usam um modelo de gols Dixon–Coles que corrige o viés de poucos gols e empates (Dixon & Coles, 1997).", ref_host: "Os anfitriões têm vantagem de casa — baseada na pesquisa sobre vantagem de casa (Pollard, 1986); o tamanho é calibrado em Copas anteriores.", sm_footer: "Dados atualizados em {date}. A Probaball não é afiliada nem endossada pela FIFA.",
    hm_title: "Como a Probaball calcula?", hm_subtitle: "O modelo por trás dos números, em resumo", hm_h_idea: "A ideia", hm_idea: "Ninguém sabe como a Copa termina. Então, em vez de adivinhar um vencedor, a Probaball joga o torneio inteiro repetidamente – milhares de vezes. Seleções mais fortes vencem mais, e a frequência com que uma seleção chega a uma fase vira a sua probabilidade.", hm_h_strength: "Quão forte é uma seleção?", hm_strength: "A força de cada seleção é uma mistura ponderada (47,5 % rankings, 47,5 % casas de apostas, 5 % especialistas):", hm_li_fifa: "Rankings – um rating Elo de ~50 000 jogos internacionais (o ranking FIFA não acrescentou nada nos testes).", hm_li_books: "Casas de apostas – odds de {books}, convertidas em probabilidades.", hm_li_experts: "Especialistas – {n} analistas e modelos conhecidos (ex.: ESPN, Lineker, Opta).", hm_blend: "Combinamos os três num único valor de força.", hm_h_match: "Como um jogo é decidido?", hm_match: "Os gols são sorteados ao acaso (um modelo de Poisson) em que a seleção mais forte marca mais. Os anfitriões têm vantagem na fase de grupos; empates no mata-mata vão para os pênaltis.", hm_h_conviction: "Jogos fixados", hm_conviction: "Convicto de um resultado? Adicione um jogo fixado: a sua seleção vence sempre que se enfrentarem, e você vê o impacto nas probabilidades.", hm_h_note: "Bom saber", hm_note: "Isto é um modelo, não uma profecia. A Probaball não é afiliada nem endossada pela FIFA.",
    cc_eyebrow: "Sua seleção", cc_stat: "{pct} de vencer a Copa", cc_change: "Essa não é minha seleção — trocar", set_myteam: "Definir como minha seleção", is_myteam: "✓ Sua seleção",
    how_link: "Como a Probaball calcula?", code_link: "Código aberto", code_title: "Código aberto", code_subtitle: "Todo o modelo e este site são abertos", code_lede: "Uma previsão é tão confiável quanto transparente. Por isso, toda a Probaball — os dados, o modelo, a simulação e esta aplicação web — é de código aberto sob licença MIT. Examine, questione, reutilize.", code_cta: "Ver o código no GitHub →", code_what_h: "O que há no repositório", code_what_data: "Ingestão de dados — Elo de ~50 000 jogos internacionais, odds de casas de apostas e palpites de especialistas, combinados na força de cada seleção.", code_what_model: "O modelo — um motor Monte Carlo que joga o torneio de 48 seleções dezenas de milhares de vezes.", code_what_backtest: "Backtest e calibração — pontuação fora da amostra (RPS) que arbitra cada mudança do modelo.", code_what_web: "A aplicação web — este site (React + Vite), em seis idiomas.", code_data_h: "Dados e licença", code_data: "Construído sobre fontes abertas e públicas. Licença MIT. Uma previsão estatística, não um palpite certo — e não afiliada nem endossada pela FIFA.", theme_day: "☀️ Dia", theme_night: "🌙 Noite", lang_label: "Idioma",
    faq_q1: "Como a Probaball calcula quem vence a Copa do Mundo 2026?", faq_a1: "A Probaball é uma simulação de data science (Monte Carlo) que joga toda a Copa do Mundo 2026 dezenas de milhares de vezes. A força de cada seleção é uma mistura ponderada de três fontes independentes — rankings de seleções (Elo, calculado a partir de ~50 000 jogos), odds das casas de apostas e palpites de {n} especialistas — e os jogos são decididos por um modelo de gols Dixon-Coles na chave oficial. A proporção de simulações vencidas é a probabilidade.",
    faq_q2: "Quem são os favoritos para vencer a Copa do Mundo 2026?", faq_a2: "Na simulação da Probaball, {fav} é favorito com {favPct}, seguido de {second} e {third}. A ordem combina ranking, odds e palpites de especialistas.",
    faq_q3: "Em que se baseiam as odds da Probaball?", faq_a3: "Três fontes são ponderadas (47,5% rankings, 47,5% casas de apostas, 5% especialistas): rankings liderados pelo Elo (o ranking da FIFA não acrescentou nada nos nossos testes), odds sem margem de {books}, e previsões de {n} especialistas e modelos estatísticos.",
    faq_q4: "Posso fazer a minha própria simulação?", faq_a4: "Sim. Você pode ajustar os parâmetros e forçar o resultado de jogos específicos, e rodar de novo a simulação para ver como as probabilidades mudam.",
    faq_q5: "A Probaball é afiliada à FIFA?", faq_a5: "Não. A Probaball é um projeto independente de data science e não é afiliada nem endossada pela FIFA.",
    faq_q6: 'Quão avançado é o modelo — e quão preciso?', faq_a6: 'A Probaball combina muitos sinais independentes numa única previsão, parecido com a média de muitas pesquisas (um “poll of polls”). Usa um Elo de ~50 000 jogos, as odds do mercado, modelos de especialistas, um modelo de gols Dixon-Coles e a chave oficial. Importante: cada melhoria é testada contra resultados históricos (fora da amostra, via Ranked Probability Score) e o que não prevê melhor é descartado — o ranking da FIFA e um modelo de ataque/defesa não acrescentaram nada. Mas são probabilidades, não certezas: o futebol é muito aleatório, e até um grande favorito costuma ter menos de 20% de vencer o torneio.',
    tm_elo: 'Rating Elo', gm_results: 'Resultados prováveis', gm_matchday: 'Rodada {n}', gm_draw: 'Empate', gm_wins: '{team} vence', gm_as_pred: 'como previsto', gm_upset: 'surpresa', gm_detail: 'detalhe', mm_score: 'Resultado mais provável: {a}–{b}', mm_prematch: 'Probabilidades do modelo antes do jogo', gm_likely: 'prov. {hg}–{ag}',
    back_home: "← Voltar", page_team_title: "{team} – chance de vencer a Copa do Mundo 2026", page_group_title: "Grupo {g} – Copa do Mundo 2026",
  },
  de: {
    lede_head: 'So wird die WM 2026 verlaufen.', lede_basis_pre: 'Auf Basis von Ranglisten, führenden Buchmachern und Experten hat Krukis Data Science ein kombiniertes Simulationsmodell gebaut und ', lede_count: 'spielt das Turnier {n}-mal jeden Tag', lede_basis_post: '. So ging es aus.', lede_cta_pre: 'Hast du zu bestimmten Spielen eine eigene Meinung? Du kannst ', lede_cta_link: 'deine eigene Simulation starten', lede_cta_post: '.',
    lede_exp: "Deine eigene Simulation. Wir haben das Turnier {n}-mal mit deinen Anpassungen gespielt{forced}. So ging es aus.",
    lede_loading: 'So wird die WM 2026 verlaufen. Auf Basis von Ranglisten, Buchmachern und Experten hat Krukis Data Science ein kombiniertes Simulationsmodell gebaut.',
    forced_suffix: " und {n} entschiedenen Spielen",
    loading: "Simulation wird geladen…",
    see_sources: "Quellen ansehen", basis_date: "Daten {date}", error_load: "Daten konnten nicht geladen werden: {error}",
    sec_champion: "Weltmeister", sec_groups: "Gruppenphase", sec_bracket: "K.-o.-Baum", sec_experiment: "Deine eigene Simulation", sec_faq: "Häufige Fragen",
    hint_team: "Klicke auf ein Team für Details.", hint_group: "Klicke auf eine Gruppe für Spielprognosen und Tabelle.",
    groups_legend: "Der Balken zeigt die Aufstiegschance: gefüllter Teil = Top 2 (direkt), heller Teil = 3. Platz (die 8 besten Gruppendritten von 12 ziehen ebenfalls weiter).",
    bracket_help: "Der Durchlauf, der das erwartete Ergebnis am besten zeigt: die wahrscheinlichsten Teams in jeder Runde. Klicke für einen neuen.",
    reroll: "↻ Neuer Ausgang", experiment_hint: "Ändere das Modell und starte deine eigene Simulation.",
    col_team: "Team", col_champion: "Meister", col_final: "Finale", col_semi: "Halbf.", col_quarter: "Viertelf.", col_r16: "Achtelf.",
    show_all: "Alle {n} Teams", show_top10: "Top 10 anzeigen",
    group_label: "Gruppe {g}", details: "Details →", g_first: "1.", g_second: "2.", g_third: "3.", g_fourth: "4.", g_top2: "Top 2", g_avg: "Ø Platz",
    ctrl_params: "Modellparameter", ctrl_goal_scale: "Favoriten-Vorteil", ctrl_goal_scale_hint: "Wie stark der Stärkeunterschied entscheidet. Höher → Favoriten gewinnen öfter.", ctrl_base_goals: "Tore pro Spiel", ctrl_base_goals_hint: "Erwartete Tore in einem ausgeglichenen Spiel. Höher → mehr Tore und mehr Zufall.", ctrl_home_adv: "Heimvorteil", ctrl_home_adv_hint: "Wie groß der Vorteil der Gastgeber (USA, Mexiko, Kanada) in der Gruppenphase ist.", ctrl_rho: "Unentschieden-Neigung", ctrl_rho_hint: "Höher → mehr Unentschieden und torarme Spiele.",
    ctrl_run: "Meine Simulation starten (1000)", ctrl_running: "Simuliere…", ctrl_reset: "Zurücksetzen", ctrl_back: "← Zurück zum Standard", ctrl_conviction: "Ein Spiel entscheiden", ctrl_conviction_hint: " — wähle ein Team, das ein anderes immer schlägt",
    cv_winner_ph: "Siegerteam…", cv_beats: "schlägt", cv_opponent_ph: "Gegner…", cv_x_wins: "{team} gewinnt", cv_add: "+ Hinzufügen", cv_empty: "Noch keine Spiele entschieden. Wähle ein Team, das ein anderes immer schlägt – treffen sie in der Simulation aufeinander, gewinnt dein Team.",
    close: "Schließen",
    tm_subtitle: "{group} · effektive Stärke {r}", tm_matches: "Spiele", tm_chart_h: "Verlauf der Titelchance", tm_ko_note: "Prognose · {pct} wahrscheinlich", tm_ko_adv: "{pct} weiter", tm_ko_split: "{reg} in 90′ · {et} Verl./Elfm.", ko_reg_lbl: "in 90′", ko_et_lbl: "Verl./Elfm.", tm_pred: "{pct} Sieg", tm_placement: "Endplatzierung", tm_placement_hint: "Anteil der Simulationen je Endplatzierung (1 = Meister … 33–48 = in der Gruppe ausgeschieden).", tm_x_placement: "Platzierung (1–48)", tm_y_share: "Wahrscheinlichkeit", col_change_7d: "Veränderung", col_change_7d_hint: "Veränderung der Titelchance seit Turnierbeginn", eliminated_hint: "Ausgeschieden — 0 % Chance weiterzukommen", trend_label: "Diese Woche", read_more: "Mehr lesen", read_less: "Weniger anzeigen", tm_champ_up: "Wahrscheinlicher Meister als zu Turnierbeginn, von {from}% auf {to}%", tm_champ_down: "Unwahrscheinlicher Meister als zu Turnierbeginn, von {from}% auf {to}%", tm_vs_week: "{v} seit Turnierbeginn", tm_progress: "Wie weit das Team kommt", tm_x_round: "K.-o.-Runde", tm_group_place: "Platzierung in der Gruppe", tm_x_group: "Position in der Gruppe", tm_rnd_final: "Finale", tm_rnd_semi: "Halbf.", tm_rnd_quarter: "Viertelf.", tm_rnd_r16: "R16", tm_rnd_r32: "R32", tm_rnd_group: "Gruppe", tm_no_group: "Keine Gruppendaten.", tm_rnd_third: "Platz 3", tm_pens: "Elfm.", tm_basis: "Grundlage (47.5 % · 47.5 % · 5 %)", tm_fifa: "FIFA-Rangliste", tm_fifa_rank: "#{r} von 48 im Turnier", tm_world_rank: " · Weltrang #{r}", tm_books: "Buchmacher", tm_book_chance: "≈ {pct} Titelchance", tm_experts: "Experten", tm_expert_weight: "Gewicht {pct}", tm_book_odds: "Buchmacher-Quoten (Titel)", tm_expert_preds: "Experten-Tipps", tm_no_experts: "Keiner der {n} Experten hat dieses Team getippt.",
    role_winner: "Meister", role_finalist: "Finalist", role_semifinalist: "Halbfinale",
    gm_subtitle: "Simulierte Endplatzierung – Wahrscheinlichkeit je Position", gm_note: "Dunklere Zone = Top 2 (direkte Qualifikation); hellere = 3. Platz. Die acht besten Gruppendritten von zwölf ziehen ebenfalls in die Runde der 32 ein.",
    eval_link: "Auswertung", eval_title: "Wie gut ist die Prognose?", eval_subtitle: "Die Vorhersagen des Modells vor dem Spiel, an den Ergebnissen gemessen",
    eval_empty: "Es wurde noch kein Spiel ausgetragen — schau wieder vorbei, sobald das Turnier läuft.",
    eval_chart_h: "Wie sich das Titelrennen verschoben hat", eval_chart_help: "Die Titelchance jedes Teams, Tag für Tag seit dem 30. Mai.", eval_rps: "Durchschnitts-RPS", eval_lower_better: "niedriger ist besser · 0 = perfekt", eval_games: "Bewertete Spiele", eval_so_far: "Gruppenphase bisher",
    eval_called: "Favorit getroffen", eval_called_exp: "erwartet ~{exp}", eval_upsets: "Überraschungen", eval_upsets_exp: "erwartet ~{exp}",
    eval_rps_info: "Der Ranked Probability Score ist die wissenschaftliche Standardmetrik für Fußballprognosen: Er belohnt Wahrscheinlichkeit nahe am tatsächlichen Ergebnis und respektiert die Reihenfolge Heim–Unentschieden–Auswärts, sodass ein knapper Fehlgriff weniger bestraft wird als ein grober. Niedriger ist besser; 0 ist eine perfekte Vorhersage.",
    eval_bench: "Zum Vergleich: veröffentlichte Modelle liegen im Ligafußball bei etwa 0,19–0,22 RPS, scharfe Buchmacherquoten bei rund 0,20. Internationale Turniere verhalten sich anders — also als grober Richtwert zu verstehen, nicht als Ziel.",
    eval_cite: "Metrik: Constantinou & Fenton (2012), Journal of Quantitative Analysis in Sports 8(1).",
    eval_upset_inline: "Bisher waren {m} von {n} Spielen Überraschungen — ein Ausgang, den das Modell unter {p} ansetzte. Es erwartete etwa {exp}, also liegen die Ergebnisse im Rahmen der Erwartungen.",
    eval_upset_more: "Bisher waren {m} von {n} Spielen Überraschungen — ein Ausgang, den das Modell unter {p} ansetzte. Es erwartete etwa {exp}, also ging es turbulenter zu als erwartet.",
    eval_upset_fewer: "Bisher waren nur {m} von {n} Spielen Überraschungen — ein Ausgang, den das Modell unter {p} ansetzte. Es erwartete etwa {exp}, also lief es erwartungsgemäßer als gedacht.",
    eval_calib_h: "Kalibrierung", eval_calib_help: "Wenn das Modell einen Ausgang mit X% ansetzt, tritt er in X% der Fälle ein? Punkte auf der Diagonale sind perfekt kalibriert; oberhalb trat es häufiger ein als vorhergesagt, unterhalb seltener.",
    eval_calib_x: "Vorhergesagt %", eval_calib_y: "Beobachtet %", eval_calib_ideal: "Perfekte Kalibrierung", eval_calib_model: "Modell bisher",
    eval_smallN: "Bei nur einer Handvoll Spiele sind die Punkte verrauscht — sie stabilisieren sich mit weiteren Partien.",
    eval_games_h: "Spiel für Spiel", eval_p_actual: "Modell gab {p}",
    sm_title: "Quellen", sm_subtitle: "Die Wahrscheinlichkeiten gewichten 47,5 % Rankings, 47,5 % Buchmacher, 5 % Experten", sm_rank_h: "Team-Rankings (Elo)", sm_fifa_desc: "Die Stärke stammt aus einer Elo-Wertung über ~50 000 Länderspiele. (Das FIFA-Ranking wurde getestet, brachte aber nichts über Elo hinaus und wird nicht verwendet.)", sm_books: "Führende Buchmacher", sm_books_desc: "Quoten Ende Mai 2026 erhoben.", sm_experts_n: "Experten ({n})", sm_tips: "Tippt auf Titel", sm_goal_h: "Tormodell (Unentschieden)", sm_host_h: "Heimvorteil (Gastgeber)", ref_elo: "Die Rankings nutzen die World-Football-Elo-Methode (eloratings.net).", ref_books: "Marktquoten zählen zu den treffsichersten Ergebnisprognosen (Forrest, Goddard & Simmons, 2005).", ref_goal: "Die Ergebnisse nutzen ein Dixon–Coles-Tormodell, das die Verzerrung bei wenigen Toren und Unentschieden korrigiert (Dixon & Coles, 1997).", ref_host: "Gastgeber haben einen Heimvorteil — gestützt auf die Heimvorteil-Forschung (Pollard, 1986); die Größe ist an früheren WMs kalibriert.", sm_footer: "Daten aktualisiert am {date}. Probaball ist nicht mit der FIFA verbunden oder von ihr unterstützt.",
    hm_title: "Wie rechnet Probaball?", hm_subtitle: "Das Modell hinter den Zahlen, kurz erklärt", hm_h_idea: "Die Idee", hm_idea: "Niemand weiß, wie die WM endet. Statt einen Sieger zu raten, spielt Probaball das ganze Turnier immer wieder durch – tausendfach. Stärkere Teams gewinnen öfter, und wie oft ein Team eine Runde erreicht, wird zu seiner Wahrscheinlichkeit.", hm_h_strength: "Wie stark ist ein Team?", hm_strength: "Die Stärke jedes Teams ist eine gewichtete Mischung (47,5 % Rankings, 47,5 % Buchmacher, 5 % Experten):", hm_li_fifa: "Rankings – eine Elo-Wertung aus ~50 000 Länderspielen (das FIFA-Ranking brachte in Tests nichts Zusätzliches).", hm_li_books: "Buchmacher – Titelquoten von {books}, in Wahrscheinlichkeiten umgerechnet.", hm_li_experts: "Experten – {n} bekannte Tipper und Modelle (z. B. ESPN, Lineker, Opta).", hm_blend: "Wir fassen die drei zu einem Stärkewert zusammen.", hm_h_match: "Wie wird ein Spiel entschieden?", hm_match: "Tore werden zufällig gezogen (ein Poisson-Modell), wobei das stärkere Team mehr erzielt. Gastgeber haben in der Gruppenphase Heimvorteil; Unentschieden im K.-o. werden im Elfmeterschießen entschieden.", hm_h_conviction: "Festgelegte Spiele", hm_conviction: "Von einem Ergebnis überzeugt? Füge ein festgelegtes Spiel hinzu – dein Team gewinnt dann jedes Aufeinandertreffen, und du siehst, wie sich die Quoten ändern.", hm_h_note: "Gut zu wissen", hm_note: "Das ist ein Modell, keine Prophezeiung. Probaball ist nicht mit der FIFA verbunden oder von ihr unterstützt.",
    cc_eyebrow: "Dein Team", cc_stat: "{pct} auf den WM-Titel", cc_change: "Nicht mein Team — ändern", set_myteam: "Als mein Team festlegen", is_myteam: "✓ Dein Team",
    how_link: "Wie rechnet Probaball?", code_link: "Open Source", code_title: "Open Source", code_subtitle: "Das ganze Modell und diese Seite sind offen", code_lede: "Eine Prognose ist nur so vertrauenswürdig wie sie transparent ist. Deshalb ist ganz Probaball — die Daten, das Modell, die Simulation und diese Web-App — Open Source unter der MIT-Lizenz. Prüfe es, hinterfrage es, nutze es weiter.", code_cta: "Den Code auf GitHub ansehen →", code_what_h: "Was im Repo steckt", code_what_data: "Datenaufnahme — Elo aus ~50 000 Länderspielen, Buchmacherquoten und Expertentipps, zu einer Teamstärke kombiniert.", code_what_model: "Das Modell — eine Monte-Carlo-Engine, die das Turnier mit 48 Teams zehntausendfach durchspielt.", code_what_backtest: "Backtest & Kalibrierung — Out-of-Sample-Bewertung (RPS), die jede Modelländerung überprüft.", code_what_web: "Die Web-App — diese Seite (React + Vite), in sechs Sprachen.", code_data_h: "Daten & Lizenz", code_data: "Auf offenen und öffentlichen Quellen aufgebaut. MIT-lizenziert. Eine statistische Prognose, keine Vorhersage — und nicht mit der FIFA verbunden oder von ihr unterstützt.", theme_day: "☀️ Tag", theme_night: "🌙 Nacht", lang_label: "Sprache",
    faq_q1: "Wie ermittelt Probaball, wer die WM 2026 gewinnt?", faq_a1: "Probaball ist eine Data-Science-Simulation (Monte Carlo), die die gesamte WM 2026 zehntausendfach durchspielt. Die Stärke jedes Teams ist eine gewichtete Mischung aus drei unabhängigen Quellen — Teamranglisten (Elo, aus ~50.000 Länderspielen berechnet), Buchmacherquoten und den Tipps von {n} Experten — und die Spiele werden mit einem Dixon-Coles-Tormodell im offiziellen K.-o.-Baum entschieden. Der Anteil gewonnener Simulationen ist die Wahrscheinlichkeit.",
    faq_q2: "Wer sind die Favoriten auf den WM-Titel 2026?", faq_a2: "In Probaballs Simulation ist {fav} mit {favPct} Favorit, gefolgt von {second} und {third}. Die Reihenfolge kombiniert Rangliste, Quoten und Experten-Tipps.",
    faq_q3: "Worauf basieren die Quoten von Probaball?", faq_a3: "Drei Quellen werden gewichtet (47,5 % Ranglisten, 47,5 % Buchmacher, 5 % Experten): Ranglisten angeführt von Elo (die FIFA-Rangliste brachte in unseren Tests keinen Mehrwert), entmarginalisierte Titelquoten von {books} und Prognosen von {n} Experten und statistischen Modellen.",
    faq_q4: "Kann ich meine eigene Simulation starten?", faq_a4: "Ja. Du kannst die Parameter anpassen und den Ausgang einzelner Spiele erzwingen und die Simulation neu starten, um zu sehen, wie sich die Wahrscheinlichkeiten ändern.",
    faq_q5: "Ist Probaball mit der FIFA verbunden?", faq_a5: "Nein. Probaball ist ein unabhängiges Data-Science-Projekt und nicht mit der FIFA verbunden oder von ihr unterstützt.",
    faq_q6: 'Wie ausgefeilt ist das Modell — und wie treffsicher?', faq_a6: 'Probaball fügt viele unabhängige Signale zu einer Prognose zusammen — ähnlich wie der Durchschnitt vieler Umfragen (ein “poll of polls”). Es nutzt ein Elo aus ~50.000 Länderspielen, Marktquoten, Expertenmodelle, ein Dixon-Coles-Tormodell und den offiziellen K.-o.-Baum. Wichtig: jede Verbesserung wird an historischen Ergebnissen getestet (out-of-sample, per Ranked Probability Score), und was nicht besser vorhersagt, fliegt raus — die FIFA-Rangliste und ein Angriffs-/Abwehrmodell brachten keinen Mehrwert. Aber es sind Wahrscheinlichkeiten, keine Gewissheiten: Fußball ist sehr zufallsbehaftet, und selbst ein großer Favorit liegt meist unter 20 % für den Turniersieg.',
    tm_elo: 'Elo-Wertung', gm_results: 'Wahrscheinliche Ausgänge', gm_matchday: 'Spieltag {n}', gm_draw: 'Unentschieden', gm_wins: '{team} gewinnt', gm_as_pred: 'wie erwartet', gm_upset: 'Überraschung', gm_detail: 'Detail', mm_score: 'Wahrscheinlichstes Ergebnis: {a}–{b}', mm_prematch: 'Modell-Quoten vor dem Spiel', gm_likely: 'wahrsch. {hg}–{ag}',
    back_home: "← Zurück", page_team_title: "{team} – Chance auf den WM-Titel 2026", page_group_title: "Gruppe {g} – WM 2026",
  },
};

// English lives at the root; the other languages (incl. Swedish at /sv/) live
// under a /<lang>/ prefix.
const ROOT_LANG = "en";
const PREFIXED = SUPPORTED.filter((l) => l !== ROOT_LANG);

// The language a pathname encodes via its prefix (e.g. "/sv/lag/x" -> "sv"),
// or null when there is no prefix (English root).
export function pathLang(pathname) {
  const p =
    pathname ?? (typeof window !== "undefined" ? window.location.pathname : "/");
  const m = p.match(/^\/([a-z]{2})(?=\/|$)/);
  return m && PREFIXED.includes(m[1]) ? m[1] : null;
}

// Drop any language prefix, leaving the bare route ("/", "/lag/x/", ...).
export function stripLangPrefix(pathname) {
  const bare = pathname.replace(/^\/([a-z]{2})(?=\/|$)/, (s, l) =>
    PREFIXED.includes(l) ? "" : s
  );
  return bare || "/";
}

// Re-attach the prefix for a target language (English keeps the bare route).
export function localizedPath(pathname, lang) {
  const bare = stripLangPrefix(pathname);
  if (lang === ROOT_LANG) return bare;
  return bare === "/" ? `/${lang}/` : `/${lang}${bare}`;
}

export function detectLang() {
  const fromUrl = pathLang();
  if (fromUrl) return fromUrl;
  const saved = localStorage.getItem("lang");
  if (saved && SUPPORTED.includes(saved)) return saved;
  for (const l of navigator.languages || [navigator.language || ""]) {
    const base = l.split("-")[0].toLowerCase();
    if (SUPPORTED.includes(base)) return base;
  }
  return "en";
}

const I18nCtx = createContext(null);

export function I18nProvider({ children }) {
  const [lang, setLang] = useState(detectLang);
  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key, vars) => {
    let s = STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? STRINGS.sv[key] ?? key;
    if (vars) for (const k in vars) s = s.split(`{${k}}`).join(vars[k]);
    return s;
  };
  const tn = (svName) =>
    lang === "sv" ? svName : TEAM_NAMES[lang]?.[svName] ?? svName;

  return (
    <I18nCtx.Provider value={{ lang, setLang, t, tn }}>
      {children}
    </I18nCtx.Provider>
  );
}

export const useI18n = () => useContext(I18nCtx);
